[package]
name = "shadowlands-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.shadowlands]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.1"
default-features = false
