[package]
name = "market-db-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.market-db]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.46.0"
default-features = false
