/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function GraveHp({ position, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/Grave_1_HP.glb');
  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='HP_Grave_1'
          castShadow
          receiveShadow
          geometry={nodes.HP_Grave_1.geometry}
          material={materials.Rock3}
          position={position}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/game/Grave_1_HP.glb');
