/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export function Grave({ position, color, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/Grave_1.glb');

  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Cube'
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={position}
        >
          <meshStandardMaterial color={color} transparent />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/game/Grave_1.glb');
