/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF } from '@react-three/drei';

export function Grave({ position, ...props }: any) {
  const [hovered, hover] = useState(false);
  const { nodes, materials } = useGLTF('/game/Grave_1.glb');

  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto';
  }, [hovered]);
  return (
    <group {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          onPointerOver={(event) => hover(true)}
          onPointerOut={(event) => hover(false)}
          name='Cube'
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={position}
        >
          <meshStandardMaterial
            color={hovered ? 'blue' : 'white'}
            transparent
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('/game/Grave_1.glb');
