/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model101(props) {
  const { nodes, materials } = useGLTF("/game/Land_1_01.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[3.837, 1.016, -3.726]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[5.825, 1.016, -5.757]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[5.418, 1.016, -6.536]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder002_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[7.518, 1.016, -7.687]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[5.57, 1.016, -5.026]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-6.024, 1.016, 1.476]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-8.466, 1.016, 1.05]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-7.271, 0.888, 5.865]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-6.62, 0.56, 6.406]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-7.653, 0.921, 6.603]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[-7.89, 0.768, 5.621]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[5.52, 0.907, 7.182]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[5.861, 0.757, 5.914]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder012_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[6.446, 0.894, 6.938]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder013_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[6.95, 0.632, 5.147]} scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder014_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[9.275, 0.892, 4.939]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder015_2.geometry}
          material={materials.Pins}
        />
      </group>
      <group position={[8.104, 0.922, 5.085]} scale={0.138}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_1.geometry}
          material={materials.Tronc}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder016_2.geometry}
          material={materials.Pins}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.Rock1}
        position={[-3.419, 0.987, 0.095]}
        rotation={[0, 0.474, 0]}
        scale={[0.777, 0.261, 0.396]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials.Rock1}
        position={[-3.16, 0.961, -0.564]}
        rotation={[-0.038, 0.1, -0.295]}
        scale={[0.497, 0.167, 0.253]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials.Rock1}
        position={[-6.112, 0.987, 5.264]}
        rotation={[0, -1.209, 0]}
        scale={[0.777, 0.261, 0.396]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere003.geometry}
        material={materials.Rock1}
        position={[-5.485, 0.834, 5.595]}
        rotation={[-1.869, -1.532, -2.168]}
        scale={[0.271, 0.167, 0.253]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere004.geometry}
        material={materials.Rock1}
        position={[-6.602, 0.905, 5.673]}
        rotation={[-3.034, -1.212, 2.943]}
        scale={[0.413, 0.139, 0.349]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere005.geometry}
        material={materials.Rock1}
        position={[-8.287, 1.069, 7.3]}
        rotation={[-1.869, -1.532, -2.168]}
        scale={[0.166, 0.102, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere006.geometry}
        material={materials.Rock1}
        position={[-8.131, 1.069, 7.045]}
        rotation={[-1.869, -1.532, -2.168]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere007.geometry}
        material={materials.Rock1}
        position={[-8.052, 1.033, 7.398]}
        rotation={[-0.088, -1.13, -0.378]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere008.geometry}
        material={materials.Rock1}
        position={[7.127, 1.199, -6.475]}
        rotation={[Math.PI, -0.529, Math.PI]}
        scale={[0.777, 0.261, 0.396]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere009.geometry}
        material={materials.Rock1}
        position={[7.328, 1.046, -6.084]}
        rotation={[-3.104, -0.155, 2.849]}
        scale={[0.553, 0.203, 0.308]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere010.geometry}
        material={materials.Rock1}
        position={[6.642, 1.117, -6.89]}
        rotation={[-3.103, 0.189, 2.836]}
        scale={[0.413, 0.139, 0.211]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere011.geometry}
        material={materials.Rock1}
        position={[6.626, 1.069, 7.787]}
        rotation={[-1.869, -1.532, -2.168]}
        scale={[0.166, 0.102, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere012.geometry}
        material={materials.Rock1}
        position={[6.783, 1.069, 7.533]}
        rotation={[-1.869, -1.532, -2.168]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials.Rock1}
        position={[6.861, 1.033, 7.885]}
        rotation={[-0.088, -1.13, -0.378]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere014.geometry}
        material={materials.Rock1}
        position={[7.419, 1.069, 6.807]}
        rotation={[-3.087, -0.817, 2.883]}
        scale={[0.166, 0.102, 0.155]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere015.geometry}
        material={materials.Rock1}
        position={[7.707, 1.069, 6.725]}
        rotation={[-3.087, -0.817, 2.883]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere016.geometry}
        material={materials.Rock1}
        position={[7.526, 1.033, 7.038]}
        rotation={[-3.016, -1.267, 2.963]}
        scale={[0.135, 0.083, 0.126]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere017.geometry}
        material={materials.Rock1}
        position={[7.322, 1.069, 7.363]}
        rotation={[-0.09, -1.142, -0.381]}
        scale={[0.541, 0.195, 0.296]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crane.geometry}
        material={materials.Bone}
        position={[0.325, 4.642, -6.746]}
        rotation={[-0.248, 0, 0]}
      />
      <group position={[0, 1.016, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Roche}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_1.geometry}
          material={materials.HerbeMorte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_2.geometry}
          material={materials.HerbeVerte}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_3.geometry}
          material={materials.Sable}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube_4.geometry}
          material={materials.Rock1}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/game/Land_1_01.glb");
