/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function BankStandard({ position, color, rotation, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/BankStandard.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Bank512'
        castShadow
        receiveShadow
        geometry={nodes.Bank512.geometry}
        material={materials.BankGeneral}
        position={position}
        scale={[0.5, 0.5, 0.5]}
        rotation={rotation}
      />
    </group>
  );
}

useGLTF.preload('/game/BankStandard.glb');
