/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function BankEmpty({ position, color, rotation, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/BankEmpty.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Bank512'
        castShadow
        receiveShadow
        geometry={nodes.Bank512.geometry}
        material={materials.BankGeneral}
        position={position}
        scale={[0.5, 0.5, 0.5]}
        rotation={rotation}
      >
        <meshStandardMaterial color={color} transparent />
      </mesh>
    </group>
  );
}

useGLTF.preload('/game/BankEmpty.glb');
