/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useAnimations, useGLTF } from '@react-three/drei';
import { Color, MeshStandardMaterial } from 'three';

export function BankR2({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Bank+2.glb');
  const { actions } = useAnimations(animations, group);

  const position = [-3.0777, 1.0154, -3.8426];
  const rotation = [0, 0.2688036, 0];

  const emptyMaterial = new MeshStandardMaterial();
  emptyMaterial.color = new Color(color);
  emptyMaterial.transparent = true;
  emptyMaterial.opacity = 0.2;

  useEffect(() => {
    actions.BankAction.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <spotLight
          position={[position[0], position[1] + 0.2, position[2] + 0.3]}
          color={'aqua'}
          intensity={Math.PI * 2}
        />
      )}
      <group name='Scene'>
        <group
          name='Bank_+2'
          position={[-2.912, 1.92, -3.635]}
          rotation={[0, 0.267, 0]}
        >
          <mesh
            name='Cube002'
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={color ? emptyMaterial : materials.BankFace_2}
          />
          <mesh
            name='Cube002_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={color ? emptyMaterial : materials.BankSoubassement_2}
          />
          <mesh
            name='Cube002_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={color ? emptyMaterial : materials.BankToit_1}
          />
          <mesh
            name='Cube002_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_3.geometry}
            material={color ? emptyMaterial : materials.Lumiere}
          />
          <mesh
            name='Cube002_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_4.geometry}
            material={color ? emptyMaterial : materials.BankColonnes_2}
          />
          <mesh
            name='Cube002_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_5.geometry}
            material={color ? emptyMaterial : materials.Palette}
          />
          <mesh
            name='Cube002_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_6.geometry}
            material={color ? emptyMaterial : materials.Enseigne}
          />
          <mesh
            name='Cube002_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_7.geometry}
            material={color ? emptyMaterial : materials.Floor}
          />
          <mesh
            name='Cube002_8'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_8.geometry}
            material={color ? emptyMaterial : materials.Walls}
          />
          <mesh
            name='Cube002_9'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_9.geometry}
            material={color ? emptyMaterial : materials.Ceiling}
          />
          <mesh
            name='Cube002_10'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_10.geometry}
            material={color ? emptyMaterial : materials.BlancLaque}
          />
          <mesh
            name='Cube002_11'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_11.geometry}
            material={color ? emptyMaterial : materials['SkBase.001']}
          />
          <mesh
            name='Cube002_12'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_12.geometry}
            material={color ? emptyMaterial : materials['SkShadow.001']}
          />
          <mesh
            name='Cube002_13'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_13.geometry}
            material={color ? emptyMaterial : materials['SkTeeth.001']}
          />
          <mesh
            name='Cube002_14'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_14.geometry}
            material={color ? emptyMaterial : materials.PortraitBeni}
          />
          <mesh
            name='Cube002_15'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_15.geometry}
            material={color ? emptyMaterial : materials.EGLD_Chart}
          />
          <mesh
            name='Cube002_16'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_16.geometry}
            material={color ? emptyMaterial : materials.TapisPersan}
          />
          <mesh
            name='Cube002_17'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_17.geometry}
            material={color ? emptyMaterial : materials.Classeurs}
          />
        </group>
        <group
          name='ArmatureSkeleton001'
          position={[-2.767, 1.127, -3.02]}
          scale={0.035}
        >
          <group name='LPSkeleton001'>
            <skinnedMesh
              name='Sphere002'
              geometry={nodes.Sphere002.geometry}
              material={color ? emptyMaterial : materials.SkBase}
              skeleton={nodes.Sphere002.skeleton}
            />
            <skinnedMesh
              name='Sphere002_1'
              geometry={nodes.Sphere002_1.geometry}
              material={color ? emptyMaterial : materials.SkShadow}
              skeleton={nodes.Sphere002_1.skeleton}
            />
            <skinnedMesh
              name='Sphere002_2'
              geometry={nodes.Sphere002_2.geometry}
              material={color ? emptyMaterial : materials.SkTeeth}
              skeleton={nodes.Sphere002_2.skeleton}
            />
          </group>
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <group
          name='Coffre001'
          position={[-2.613, 1.121, -2.955]}
          rotation={[0, 0.004, 0]}
          scale={0.044}
        >
          <mesh
            name='Cube011'
            castShadow
            receiveShadow
            geometry={nodes.Cube011.geometry}
            material={color ? emptyMaterial : materials.CoffreBois}
          />
          <mesh
            name='Cube011_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube011_1.geometry}
            material={color ? emptyMaterial : materials.CoffreCuirSangles}
          />
          <mesh
            name='Cube011_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube011_2.geometry}
            material={color ? emptyMaterial : materials.CoffreCuirPanneaux}
          />
          <mesh
            name='Cube011_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube011_3.geometry}
            material={color ? emptyMaterial : materials.CoffreClou}
          />
        </group>
        <mesh
          name='Token1001'
          castShadow
          receiveShadow
          geometry={nodes.Token1001.geometry}
          material={color ? emptyMaterial : materials.Token}
          position={[-3.857, 2.132, -3.278]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Token2001'
          castShadow
          receiveShadow
          geometry={nodes.Token2001.geometry}
          material={color ? emptyMaterial : materials.Token}
          position={[-1.911, 2.132, -3.805]}
          rotation={[Math.PI / 2, 0, 1.882]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/game/Bank+2.glb');
