/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Bank({ position, color, rotation, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/Bank.glb');
  return (
    <group {...props} dispose={null}>
      <spotLight position={[position[0], position[1]+0.2, position[2]]} color={'gold'} intensity={Math.PI * 10} />
      <mesh
        name='Bank512'
        castShadow
        receiveShadow
        geometry={nodes.Bank512.geometry}
        material={materials.BankGeneral}
        position={position}
        scale={[0.5, 0.5, 0.5]}
        rotation={rotation}
      >
        {color !== undefined && (
          <meshStandardMaterial color={color} transparent />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload('/game/Bank.glb');
