/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { Color, MeshStandardMaterial } from 'three';

export function CryptR2({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Crypt+2.glb');
  const { actions } = useAnimations(animations, group);

  const position = [1.8028, 1.378, -5.3541];
  const rotation = [0, -0.4952958, 0];

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  const emptyMaterial = new MeshStandardMaterial();
  emptyMaterial.color = new Color(color);
  emptyMaterial.transparent = true;
  emptyMaterial.opacity = 0.2;

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <spotLight
          position={[position[0] - 0.8, position[1] + 0.2, position[2] + 1]}
          color={'gold'}
          intensity={Math.PI * 2}
        />
      )}
      <group name='Scene'>
        <group
          name='Armature001'
          position={[1.629, 3.762, -3.95]}
          rotation={[-2.471, -1.35, -2.447]}
        >
          <skinnedMesh
            name='Cube002'
            geometry={nodes.Cube002.geometry}
            material={color ? emptyMaterial : materials.Corbeau}
            skeleton={nodes.Cube002.skeleton}
          />
          <primitive object={nodes.Bone} />
        </group>
        <group name='Crypt+2'>
          <mesh
            name='Plane004'
            castShadow
            receiveShadow
            geometry={nodes.Plane004.geometry}
            material={color ? emptyMaterial : materials['Ardoises.001']}
          />
          <mesh
            name='Plane004_1'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_1.geometry}
            material={color ? emptyMaterial : materials.Charpente}
          />
          <mesh
            name='Plane004_2'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_2.geometry}
            material={color ? emptyMaterial : materials['Colonnes.001']}
          />
          <mesh
            name='Plane004_3'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_3.geometry}
            material={color ? emptyMaterial : materials['Base.001']}
          />
          <mesh
            name='Plane004_4'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_4.geometry}
            material={color ? emptyMaterial : materials['Etage.001']}
          />
          <mesh
            name='Plane004_5'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_5.geometry}
            material={color ? emptyMaterial : materials['Vitres.001']}
          />
          <mesh
            name='Plane004_6'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_6.geometry}
            material={color ? emptyMaterial : materials['Vitraux.001']}
          />
          <mesh
            name='Plane004_7'
            castShadow
            receiveShadow
            geometry={nodes.Plane004_7.geometry}
            material={color ? emptyMaterial : materials.Porte}
          />
        </group>
        <group
          name='Intérieur+2'
          position={[1.629, 1.337, -4.953]}
          rotation={[0, -0.495, 0]}
        >
          <mesh
            name='Cube009'
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={color ? emptyMaterial : materials.Banc}
          />
          <mesh
            name='Cube009_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_1.geometry}
            material={color ? emptyMaterial : materials.Vitraux}
          />
          <mesh
            name='Cube009_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_2.geometry}
            material={color ? emptyMaterial : materials['Vitres.001']}
          />
          <mesh
            name='Cube009_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_3.geometry}
            material={color ? emptyMaterial : materials.Etagere}
          />
          <mesh
            name='Cube009_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_4.geometry}
            material={color ? emptyMaterial : materials.Estrade}
          />
          <mesh
            name='Cube009_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_5.geometry}
            material={color ? emptyMaterial : materials['SkBase.001']}
          />
          <mesh
            name='Cube009_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_6.geometry}
            material={color ? emptyMaterial : materials['SkShadow.001']}
          />
          <mesh
            name='Cube009_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_7.geometry}
            material={color ? emptyMaterial : materials['Palette.002']}
          />
          <mesh
            name='Cube009_8'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_8.geometry}
            material={color ? emptyMaterial : materials.TapisPersan}
          />
          <mesh
            name='Cube009_9'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_9.geometry}
            material={color ? emptyMaterial : materials.VieuxLivre}
          />
          <mesh
            name='Cube009_10'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_10.geometry}
            material={color ? emptyMaterial : materials.Torche}
          />
          <mesh
            name='Cube009_11'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_11.geometry}
            material={color ? emptyMaterial : materials.Material}
          />
          <mesh
            name='Cube009_12'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_12.geometry}
            material={color ? emptyMaterial : materials.PortraitBeni}
          />
          <mesh
            name='Cube009_13'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_13.geometry}
            material={color ? emptyMaterial : materials.BarDrap}
          />
          <mesh
            name='Cube009_14'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_14.geometry}
            material={color ? emptyMaterial : materials.SkBase}
          />
          <mesh
            name='Cube009_15'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_15.geometry}
            material={color ? emptyMaterial : materials.SkShadow}
          />
          <mesh
            name='Cube009_16'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_16.geometry}
            material={color ? emptyMaterial : materials.SkTeeth}
          />
          <mesh
            name='Cube009_17'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_17.geometry}
            material={color ? emptyMaterial : materials['Base.001']}
          />
          <mesh
            name='Cube009_18'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_18.geometry}
            material={color ? emptyMaterial : materials['Colonnes.001']}
          />
          <mesh
            name='Cube009_19'
            castShadow
            receiveShadow
            geometry={nodes.Cube009_19.geometry}
            material={color ? emptyMaterial : materials['Flamme.001']}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/Crypt+2.glb');
