/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function CryptStandard({ position, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/CrypteCouleur.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Crypte'
        castShadow
        receiveShadow
        geometry={nodes.Crypte.geometry}
        material={materials.Crypte}
        position={position}
        scale={[0.25, 0.25, 0.25]}
      />
    </group>
  );
}

useGLTF.preload('/game/CrypteCouleur.glb');
