/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { Color, MeshStandardMaterial } from 'three';

export function HauntedHouseR1({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/HauntedHouse+1.glb');
  const { actions } = useAnimations(animations, group);

  const position = [5.5994, 1.6568, -1.1516];
  const rotation = [0, -1.5338651598227, 0];

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  const emptyMaterial = new MeshStandardMaterial();
  emptyMaterial.color = new Color(color);
  emptyMaterial.transparent = true;
  emptyMaterial.opacity = 0.2;

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <spotLight
          position={[position[0] - 0.3, position[1] + 0.2, position[2]]}
          color={'purple'}
          intensity={Math.PI * 2}
        />
      )}
      <group name='Scene'>
        <group name='Interieur'>
          <mesh
            name='HauntedHouse004'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004.geometry}
            material={color ? emptyMaterial : materials.Palette}
          />
          <mesh
            name='HauntedHouse004_1'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_1.geometry}
            material={color ? emptyMaterial : materials.Parquet}
          />
          <mesh
            name='HauntedHouse004_2'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_2.geometry}
            material={color ? emptyMaterial : materials.TableauCadre}
          />
          <mesh
            name='HauntedHouse004_3'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_3.geometry}
            material={color ? emptyMaterial : materials.VitresLumière}
          />
          <mesh
            name='HauntedHouse004_4'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_4.geometry}
            material={color ? emptyMaterial : materials['SkBase.002']}
          />
          <mesh
            name='HauntedHouse004_5'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_5.geometry}
            material={color ? emptyMaterial : materials['SkShadow.002']}
          />
          <mesh
            name='HauntedHouse004_6'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_6.geometry}
            material={color ? emptyMaterial : materials['SkTeeth.002']}
          />
          <mesh
            name='HauntedHouse004_7'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_7.geometry}
            material={color ? emptyMaterial : materials.TapisPersan}
          />
          <mesh
            name='HauntedHouse004_8'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_8.geometry}
            material={color ? emptyMaterial : materials['Palette.001']}
          />
          <mesh
            name='HauntedHouse004_9'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_9.geometry}
            material={color ? emptyMaterial : materials.Floor}
          />
          <mesh
            name='HauntedHouse004_10'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_10.geometry}
            material={color ? emptyMaterial : materials['Palette.002']}
          />
          <mesh
            name='HauntedHouse004_11'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_11.geometry}
            material={color ? emptyMaterial : materials.LanterneVerreLumière}
          />
          <mesh
            name='HauntedHouse004_12'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_12.geometry}
            material={color ? emptyMaterial : materials.NFT135_512}
          />
          <mesh
            name='HauntedHouse004_13'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_13.geometry}
            material={color ? emptyMaterial : materials.NFT029_512}
          />
          <mesh
            name='HauntedHouse004_14'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_14.geometry}
            material={color ? emptyMaterial : materials.NFT194_512}
          />
          <mesh
            name='HauntedHouse004_15'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_15.geometry}
            material={color ? emptyMaterial : materials.NFT456_512}
          />
          <mesh
            name='HauntedHouse004_16'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse004_16.geometry}
            material={color ? emptyMaterial : materials.NFT145_512}
          />
        </group>
        <mesh
          name='Porte002'
          castShadow
          receiveShadow
          geometry={nodes.Porte002.geometry}
          material={color ? emptyMaterial : materials.Porte}
          position={[5.432, 1.746, -1.066]}
          rotation={[-Math.PI, 1.354, -Math.PI]}
        />
        <group name='HauntedHouse_1'>
          <mesh
            name='HauntedHouse014'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014.geometry}
            material={color ? emptyMaterial : materials.Facade_1}
          />
          <mesh
            name='HauntedHouse014_1'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_1.geometry}
            material={color ? emptyMaterial : materials.Soubassements_0}
          />
          <mesh
            name='HauntedHouse014_2'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_2.geometry}
            material={color ? emptyMaterial : materials.VitresLumiere}
          />
          <mesh
            name='HauntedHouse014_3'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_3.geometry}
            material={color ? emptyMaterial : materials.Toit_1}
          />
          <mesh
            name='HauntedHouse014_4'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_4.geometry}
            material={color ? emptyMaterial : materials.Boiserie_0}
          />
          <mesh
            name='HauntedHouse014_5'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_5.geometry}
            material={color ? emptyMaterial : materials.EntouragePierre_0}
          />
          <mesh
            name='HauntedHouse014_6'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse014_6.geometry}
            material={color ? emptyMaterial : materials.VitreEteinte}
          />
        </group>
        <group
          name='Armature001'
          position={[5.25, 3.451, -1.178]}
          rotation={[-3.135, -0.07, -3.139]}
        >
          <skinnedMesh
            name='ChauveSouris_1001'
            geometry={nodes.ChauveSouris_1001.geometry}
            material={color ? emptyMaterial : materials.Palette}
            skeleton={nodes.ChauveSouris_1001.skeleton}
          />
          <primitive object={nodes.Bone} />
        </group>
        <group
          name='Armature002'
          position={[5.649, 3.588, -2.208]}
          rotation={[0.025, -0.369, 0.007]}
        >
          <skinnedMesh
            name='ChauveSouris_1002'
            geometry={nodes.ChauveSouris_1002.geometry}
            material={color ? emptyMaterial : materials.Palette}
            skeleton={nodes.ChauveSouris_1002.skeleton}
          />
          <primitive object={nodes.Bone_1} />
        </group>
        <group
          name='Armature003'
          position={[5.718, 2.913, 0.634]}
          rotation={[-3.134, -0.818, -3.13]}
        >
          <skinnedMesh
            name='ChauveSouris_1003'
            geometry={nodes.ChauveSouris_1003.geometry}
            material={color ? emptyMaterial : materials.Palette}
            skeleton={nodes.ChauveSouris_1003.skeleton}
          />
          <primitive object={nodes.Bone_2} />
        </group>
        <group
          name='Armature004'
          position={[5.185, 2.514, -2.605]}
          rotation={[2.739, 0.538, -1.798]}
        >
          <skinnedMesh
            name='ChauveSouris_1008'
            geometry={nodes.ChauveSouris_1008.geometry}
            material={color ? emptyMaterial : materials.Palette}
            skeleton={nodes.ChauveSouris_1008.skeleton}
          />
          <primitive object={nodes.Bone_3} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/HauntedHouse+1.glb');
