/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function HauntedHouseR2({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/HauntedHouse+2.glb');
  const { actions } = useAnimations(animations, group);

  const position = [5.5994, 1.6568, -1.1516];
  const rotation = [0, -1.5338651598227, 0];

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <spotLight
          position={[position[0] - 0.3, position[1] + 0.2, position[2]]}
          color={'purple'}
          intensity={Math.PI * 2}
        />
      )}
      <group name='Scene'>
        <group name='HauntedHouse001'>
          <mesh
            name='HauntedHouse002'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse002.geometry}
            material={materials.Facade}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='HauntedHouse002_1'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse002_1.geometry}
            material={materials.Palette}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='HauntedHouse002_2'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse002_2.geometry}
            material={materials.VitresLumiere}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='HauntedHouse002_3'
            castShadow
            receiveShadow
            geometry={nodes.HauntedHouse002_3.geometry}
            material={materials.Toit}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
        </group>
        <group
          name='Armature006'
          position={[5.25, 3.451, -1.178]}
          rotation={[-3.135, -0.07, -3.139]}
        >
          <skinnedMesh
            name='ChauveSouris_1004'
            geometry={nodes.ChauveSouris_1004.geometry}
            material={materials.Palette}
            skeleton={nodes.ChauveSouris_1004.skeleton}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </skinnedMesh>
          <primitive object={nodes.Bone} />
        </group>
        <group
          name='Armature007'
          position={[5.649, 3.588, -2.208]}
          rotation={[0.025, -0.369, 0.007]}
        >
          <skinnedMesh
            name='ChauveSouris_1005'
            geometry={nodes.ChauveSouris_1005.geometry}
            material={materials.Palette}
            skeleton={nodes.ChauveSouris_1005.skeleton}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </skinnedMesh>
          <primitive object={nodes.Bone_1} />
        </group>
        <group
          name='Armature008'
          position={[5.718, 2.913, 0.634]}
          rotation={[-3.134, -0.818, -3.13]}
        >
          <skinnedMesh
            name='ChauveSouris_1006'
            geometry={nodes.ChauveSouris_1006.geometry}
            material={materials.Palette}
            skeleton={nodes.ChauveSouris_1006.skeleton}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </skinnedMesh>
          <primitive object={nodes.Bone_2} />
        </group>
        <group
          name='Armature009'
          position={[5.185, 2.514, -2.605]}
          rotation={[2.739, 0.538, -1.798]}
        >
          <skinnedMesh
            name='ChauveSouris_1007'
            geometry={nodes.ChauveSouris_1007.geometry}
            material={materials.Palette}
            skeleton={nodes.ChauveSouris_1007.skeleton}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </skinnedMesh>
          <primitive object={nodes.Bone_3} />
        </group>
        <mesh
          name='Porte001'
          castShadow
          receiveShadow
          geometry={nodes.Porte001.geometry}
          material={materials.Porte}
          position={[5.432, 1.746, -1.066]}
        >
          {color !== undefined && (
            <meshStandardMaterial color={color} transparent opacity={0.2} />
          )}
        </mesh>
        <group
          name='Armature011'
          position={[5.501, 1.742, -1.181]}
          rotation={[0, -1.285, 0]}
          scale={0.029}
        >
          <group name='Skeleton'>
            <skinnedMesh
              name='Sphere001'
              geometry={nodes.Sphere001.geometry}
              material={materials['SkBase.002']}
              skeleton={nodes.Sphere001.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere001_1'
              geometry={nodes.Sphere001_1.geometry}
              material={materials['SkShadow.002']}
              skeleton={nodes.Sphere001_1.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere001_2'
              geometry={nodes.Sphere001_2.geometry}
              material={materials['SkTeeth.002']}
              skeleton={nodes.Sphere001_2.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
          </group>
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/HauntedHouse+2.glb');
