/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { Color, MeshStandardMaterial } from 'three';

export function LaboR1({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Labo+1.glb');
  const { actions } = useAnimations(animations, group);

  const position = [-4.6456, 1.0172, 0.69635];
  const rotation = [0, 1.5538236, 0];

  const emptyMaterial = new MeshStandardMaterial();
  emptyMaterial.color = new Color(color);
  emptyMaterial.transparent = true;
  emptyMaterial.opacity = 0.2;

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <spotLight
          position={[position[0] + 0.8, position[1] + 0.2, position[2]]}
          color={'chartreuse'}
          intensity={Math.PI * 2}
        />
      )}
      <group name="Scene">
        <group name="Labo_1" position={[-4.244, 1.822, 0.949]}>
          <mesh
            name="Cube001"
            castShadow
            receiveShadow
            geometry={nodes.Cube001.geometry}
            material={color ? emptyMaterial : materials.Base_1}
            morphTargetDictionary={nodes.Cube001.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001.morphTargetInfluences}
          />
          <mesh
            name="Cube001_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_1.geometry}
            material={color ? emptyMaterial : materials.Cuivre_1}
            morphTargetDictionary={nodes.Cube001_1.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_1.morphTargetInfluences}
          />
          <mesh
            name="Cube001_2"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_2.geometry}
            material={color ? emptyMaterial : materials.Tuyaux}
            morphTargetDictionary={nodes.Cube001_2.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_2.morphTargetInfluences}
          />
          <mesh
            name="Cube001_3"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_3.geometry}
            material={color ? emptyMaterial : materials.Lumière}
            morphTargetDictionary={nodes.Cube001_3.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_3.morphTargetInfluences}
          />
          <mesh
            name="Cube001_4"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_4.geometry}
            material={color ? emptyMaterial : materials["SkBase.001"]}
            morphTargetDictionary={nodes.Cube001_4.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_4.morphTargetInfluences}
          />
          <mesh
            name="Cube001_5"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_5.geometry}
            material={color ? emptyMaterial : materials["SkShadow.001"]}
            morphTargetDictionary={nodes.Cube001_5.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_5.morphTargetInfluences}
          />
          <mesh
            name="Cube001_6"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_6.geometry}
            material={color ? emptyMaterial : materials["SkTeeth.001"]}
            morphTargetDictionary={nodes.Cube001_6.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_6.morphTargetInfluences}
          />
          <mesh
            name="Cube001_7"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_7.geometry}
            material={color ? emptyMaterial : materials["BlueJean.001"]}
            morphTargetDictionary={nodes.Cube001_7.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_7.morphTargetInfluences}
          />
          <mesh
            name="Cube001_8"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_8.geometry}
            material={color ? emptyMaterial : materials["PullJaquart.001"]}
            morphTargetDictionary={nodes.Cube001_8.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_8.morphTargetInfluences}
          />
          <mesh
            name="Cube001_9"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_9.geometry}
            material={color ? emptyMaterial : materials.Palette}
            morphTargetDictionary={nodes.Cube001_9.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_9.morphTargetInfluences}
          />
          <mesh
            name="Cube001_10"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_10.geometry}
            material={color ? emptyMaterial : materials["Floor.001"]}
            morphTargetDictionary={nodes.Cube001_10.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_10.morphTargetInfluences}
          />
          <mesh
            name="Cube001_11"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_11.geometry}
            material={color ? emptyMaterial : materials.PortraitProf}
            morphTargetDictionary={nodes.Cube001_11.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_11.morphTargetInfluences}
          />
          <mesh
            name="Cube001_12"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_12.geometry}
            material={color ? emptyMaterial : materials.Eprouvettes}
            morphTargetDictionary={nodes.Cube001_12.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_12.morphTargetInfluences}
          />
          <mesh
            name="Cube001_13"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_13.geometry}
            material={color ? emptyMaterial : materials["SkBase.002"]}
            morphTargetDictionary={nodes.Cube001_13.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_13.morphTargetInfluences}
          />
          <mesh
            name="Cube001_14"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_14.geometry}
            material={color ? emptyMaterial : materials["SkShadow.002"]}
            morphTargetDictionary={nodes.Cube001_14.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_14.morphTargetInfluences}
          />
          <mesh
            name="Cube001_15"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_15.geometry}
            material={color ? emptyMaterial : materials["Crayon_Tube_Rouge.001"]}
            morphTargetDictionary={nodes.Cube001_15.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_15.morphTargetInfluences}
          />
          <mesh
            name="Cube001_16"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_16.geometry}
            material={color ? emptyMaterial : materials["Crayon_Clic.002"]}
            morphTargetDictionary={nodes.Cube001_16.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_16.morphTargetInfluences}
          />
          <mesh
            name="Cube001_17"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_17.geometry}
            material={color ? emptyMaterial : materials["BlancLaque.001"]}
            morphTargetDictionary={nodes.Cube001_17.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_17.morphTargetInfluences}
          />
          <mesh
            name="Cube001_18"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_18.geometry}
            material={color ? emptyMaterial : materials.Classeurs}
            morphTargetDictionary={nodes.Cube001_18.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_18.morphTargetInfluences}
          />
          <mesh
            name="Cube001_19"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_19.geometry}
            material={color ? emptyMaterial : materials.VieuxLivre}
            morphTargetDictionary={nodes.Cube001_19.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_19.morphTargetInfluences}
          />
          <mesh
            name="Cube001_20"
            castShadow
            receiveShadow
            geometry={nodes.Cube001_20.geometry}
            material={color ? emptyMaterial : materials.SolLabo}
            morphTargetDictionary={nodes.Cube001_20.morphTargetDictionary}
            morphTargetInfluences={nodes.Cube001_20.morphTargetInfluences}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/game/Labo+1.glb");
