/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Land(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Land.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='LP_Grave_1001'
          castShadow
          receiveShadow
          geometry={nodes.LP_Grave_1001.geometry}
          material={materials.Palette}
          position={[1.509, 1.249, -2.865]}
          rotation={[0.076, -0.55, -0.143]}
          scale={0.913}
        />
        <group
          name='Caveau'
          position={[-4.295, 1.08, 5.923]}
          rotation={[Math.PI, -0.971, Math.PI]}
        >
          <mesh
            name='Cube007'
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cube007_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <mesh
          name='Fantom_1'
          castShadow
          receiveShadow
          geometry={nodes.Fantom_1.geometry}
          material={materials.Palette}
          position={[-4.522, 1.271, 5.945]}
          rotation={[3.085, 0.691, -2.992]}
        />
        <mesh
          name='Fantom_2'
          castShadow
          receiveShadow
          geometry={nodes.Fantom_2.geometry}
          material={materials.Palette}
          position={[2.706, 1.554, -3.917]}
          rotation={[-0.016, 0.214, 0.019]}
        />
        <mesh
          name='Socle'
          castShadow
          receiveShadow
          geometry={nodes.Socle.geometry}
          material={materials.Palette}
          position={[0, 1.07, 0]}
        />
        <mesh
          name='Caillou1'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1.geometry}
          material={materials.Palette}
          position={[4.237, 1.105, 5.867]}
          rotation={[3.083, -0.213, -2.295]}
          scale={0.2}
        />
        <mesh
          name='Caillou2'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2.geometry}
          material={materials.Palette}
          position={[4.391, 1.117, 5.991]}
          rotation={[0.231, 0.865, 0.644]}
          scale={0.2}
        />
        <mesh
          name='Caillou3'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3.geometry}
          material={materials.Palette}
          position={[4.368, 1.088, 6.148]}
          rotation={[-0.474, 0.465, 1.15]}
          scale={0.2}
        />
        <mesh
          name='Caillou1002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1002.geometry}
          material={materials.Palette}
          position={[5.272, 1.105, 5.348]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.2}
        />
        <mesh
          name='Caillou2002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2002.geometry}
          material={materials.Palette}
          position={[5.118, 1.117, 5.223]}
          rotation={[2.911, -0.863, -2.497]}
          scale={0.2}
        />
        <mesh
          name='Caillou3002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3002.geometry}
          material={materials.Palette}
          position={[5.141, 1.088, 5.067]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.2}
        />
        <mesh
          name='Caillou1004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1004.geometry}
          material={materials.Palette}
          position={[3.157, 1.161, -4.188]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.57}
        />
        <mesh
          name='Caillou2004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2004.geometry}
          material={materials.Palette}
          position={[2.932, 1.405, -4.553]}
          rotation={[-1.123, -0.71, -2.246]}
          scale={0.51}
        />
        <mesh
          name='Caillou3005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3005.geometry}
          material={materials.Palette}
          position={[2.892, 1.247, -4.378]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.956}
        />
        <mesh
          name='Caillou1005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1005.geometry}
          material={materials.Palette}
          position={[-4.723, 1.07, -3.368]}
          rotation={[0.305, 0.184, 0.813]}
          scale={0.57}
        />
        <mesh
          name='Caillou2005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2005.geometry}
          material={materials.Palette}
          position={[-4.948, 1.131, -3.734]}
          rotation={[-1.123, -0.71, -2.246]}
          scale={0.51}
        />
        <mesh
          name='Caillou1007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1007.geometry}
          material={materials.Palette}
          position={[-4.327, 1.482, 9.163]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.57}
        />
        <mesh
          name='Caillou2006'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2006.geometry}
          material={materials.Palette}
          position={[-4.976, 1.64, 8.757]}
          rotation={[-0.701, -1.127, -1.646]}
          scale={0.51}
        />
        <mesh
          name='Caillou3006'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3006.geometry}
          material={materials.Palette}
          position={[-4.556, 1.639, 8.978]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.956}
        />
        <mesh
          name='Caillou3007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3007.geometry}
          material={materials.Palette}
          position={[0.89, 1.447, 7.632]}
          rotation={[-3.085, -0.647, -2.752]}
          scale={0.597}
        />
        <mesh
          name='Caillou1008'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1008.geometry}
          material={materials.Palette}
          position={[0.912, 1.381, 8.048]}
          rotation={[0.058, -0.178, 0.869]}
          scale={0.57}
        />
        <mesh
          name='Caillou1010'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1010.geometry}
          material={materials.Palette}
          position={[4.455, 1.482, 0.24]}
          rotation={[3.085, -0.064, -2.287]}
          scale={0.57}
        />
        <mesh
          name='Caillou2007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2007.geometry}
          material={materials.Palette}
          position={[4.055, 1.375, 0.396]}
          rotation={[-2.179, 1.227, 1.213]}
          scale={0.51}
        />
        <mesh
          name='Caillou3008'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3008.geometry}
          material={materials.Palette}
          position={[4.252, 1.452, 0.632]}
          rotation={[-0.531, 0.274, 1.42]}
          scale={0.956}
        />
        <mesh
          name='Caillou1001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1001.geometry}
          material={materials.Palette}
          position={[-1.98, 1.194, 2.525]}
          rotation={[-0.133, -0.133, 0.016]}
        />
        <mesh
          name='Caillou2001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2001.geometry}
          material={materials.Palette}
          position={[-1.746, 1.191, 2.643]}
          rotation={[-0.214, -0.078, -0.089]}
        />
        <mesh
          name='Caillou2003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2003.geometry}
          material={materials.Palette}
          position={[-1.729, 1.233, 2.925]}
          rotation={[-0.287, 1.465, 0.153]}
          scale={1.308}
        />
        <mesh
          name='Caillou3001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3001.geometry}
          material={materials.Palette}
          position={[-1.413, 1.092, 2.363]}
          rotation={[-0.133, -0.133, 0.016]}
          scale={[0.491, 0.792, 0.792]}
        />
        <mesh
          name='Caillou3003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3003.geometry}
          material={materials.Palette}
          position={[-1.929, 1.119, 1.852]}
          rotation={[-0.159, 0.981, 0.029]}
          scale={0.54}
        />
        <mesh
          name='Caillou1003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1003.geometry}
          material={materials.Palette}
          position={[-1.528, 1.073, 2.111]}
          rotation={[0.112, 0.465, -0.224]}
          scale={0.251}
        />
        <mesh
          name='Caillou3004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3004.geometry}
          material={materials.Palette}
          position={[0.154, 1.139, 0.521]}
          rotation={[-0.697, 0.908, 1.599]}
          scale={0.54}
        />
        <mesh
          name='Caillou3009'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3009.geometry}
          material={materials.Palette}
          position={[0.355, 1.129, 0.431]}
          rotation={[-2.627, -0.638, -1.802]}
          scale={0.763}
        />
        <mesh
          name='Caillou3010'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3010.geometry}
          material={materials.Palette}
          position={[0.493, 1.129, 0.211]}
          rotation={[-2.511, 0.836, -2.622]}
          scale={0.763}
        />
        <mesh
          name='Caillou3011'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3011.geometry}
          material={materials.Palette}
          position={[0.497, 1.129, -0.012]}
          rotation={[-2.725, 0.217, -2.221]}
          scale={0.763}
        />
        <mesh
          name='Caillou3012'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3012.geometry}
          material={materials.Palette}
          position={[0.463, 1.129, -0.199]}
          rotation={[-0.928, -1.055, 0.156]}
          scale={0.763}
        />
        <mesh
          name='Caillou3013'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3013.geometry}
          material={materials.Palette}
          position={[0.388, 1.149, -0.349]}
          rotation={[-2.609, -0.68, -1.771]}
          scale={0.763}
        />
        <mesh
          name='Caillou3014'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3014.geometry}
          material={materials.Palette}
          position={[0.173, 1.149, -0.456]}
          rotation={[-0.425, -0.293, 0.886]}
          scale={0.763}
        />
        <mesh
          name='Caillou3015'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3015.geometry}
          material={materials.Palette}
          position={[-0.133, 1.149, -0.435]}
          rotation={[-2.655, -0.563, -1.851]}
          scale={0.763}
        />
        <mesh
          name='Caillou3016'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3016.geometry}
          material={materials.Palette}
          position={[-0.337, 1.149, -0.279]}
          rotation={[-2.021, -1.116, -1.049]}
          scale={0.763}
        />
        <mesh
          name='Caillou3017'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3017.geometry}
          material={materials.Palette}
          position={[-0.46, 1.149, -0.145]}
          rotation={[-0.475, -0.527, 0.763]}
          scale={0.518}
        />
        <mesh
          name='Caillou3018'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3018.geometry}
          material={materials.Palette}
          position={[-0.508, 1.149, 0.075]}
          rotation={[-1.3, -1.148, -0.26]}
          scale={0.787}
        />
        <mesh
          name='Caillou3019'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3019.geometry}
          material={materials.Palette}
          position={[-0.379, 1.149, 0.236]}
          rotation={[-0.438, -0.371, 0.848]}
          scale={0.787}
        />
        <mesh
          name='Caillou3020'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3020.geometry}
          material={materials.Palette}
          position={[-0.353, 1.117, 0.456]}
          rotation={[-2.697, 0.404, -2.311]}
          scale={0.787}
        />
        <mesh
          name='Caillou3021'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3021.geometry}
          material={materials.Palette}
          position={[-0.068, 1.117, 0.516]}
          rotation={[-0.453, 0.446, 1.223]}
          scale={0.665}
        />
        <mesh
          name='Caillou3022'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3022.geometry}
          material={materials.Palette}
          position={[2.653, 1.19, -0.164]}
          rotation={[-2.712, 0.324, -2.271]}
          scale={[0.683, 0.677, 0.568]}
        />
        <mesh
          name='Caillou3023'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3023.geometry}
          material={materials.Palette}
          position={[2.554, 1.178, -0.384]}
          rotation={[-0.505, -0.616, 0.706]}
          scale={[0.969, 0.875, 0.88]}
        />
        <mesh
          name='Caillou3024'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3024.geometry}
          material={materials.Palette}
          position={[2.137, 1.178, -0.433]}
          rotation={[-2.581, -0.733, -1.729]}
          scale={[0.845, 0.961, 0.918]}
        />
        <mesh
          name='Caillou3025'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3025.geometry}
          material={materials.Palette}
          position={[1.826, 1.178, -0.396]}
          rotation={[-1.69, -1.162, -0.685]}
          scale={[0.872, 0.803, 1.048]}
        />
        <mesh
          name='Caillou3026'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3026.geometry}
          material={materials.Palette}
          position={[1.577, 1.178, -0.331]}
          rotation={[-0.459, 0.468, 1.235]}
          scale={[0.87, 1.017, 0.837]}
        />
        <mesh
          name='Caillou3027'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3027.geometry}
          material={materials.Palette}
          position={[1.389, 1.201, -0.232]}
          rotation={[-0.49, -0.574, 0.734]}
          scale={[0.97, 0.887, 0.867]}
        />
        <mesh
          name='Caillou3028'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3028.geometry}
          material={materials.Palette}
          position={[1.296, 1.201, -0.007]}
          rotation={[-1.269, 1.144, 2.257]}
          scale={[0.864, 0.816, 1.044]}
        />
        <mesh
          name='Caillou3029'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3029.geometry}
          material={materials.Palette}
          position={[1.242, 1.201, 0.231]}
          rotation={[-0.975, -1.023, 0.088]}
          scale={[0.776, 0.687, 0.727]}
        />
        <mesh
          name='Caillou3030'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3030.geometry}
          material={materials.Palette}
          position={[1.673, 1.201, 0.532]}
          rotation={[-0.406, -0.022, 1.006]}
          scale={[0.936, 1.018, 0.77]}
        />
        <mesh
          name='Caillou3031'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3031.geometry}
          material={materials.Palette}
          position={[1.891, 1.201, 0.543]}
          rotation={[-0.842, 1.013, 1.776]}
          scale={[0.573, 0.591, 0.684]}
        />
        <mesh
          name='Caillou3032'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3032.geometry}
          material={materials.Palette}
          position={[2.208, 1.201, 0.55]}
          rotation={[-0.424, 0.279, 1.139]}
          scale={[0.923, 1.067, 0.82]}
        />
        <mesh
          name='Caillou3033'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3033.geometry}
          material={materials.Palette}
          position={[2.397, 1.201, 0.398]}
          rotation={[-1.101, 1.112, 2.071]}
          scale={[0.883, 0.859, 1.068]}
        />
        <mesh
          name='Caillou3034'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3034.geometry}
          material={materials.Palette}
          position={[2.478, 1.163, 0.076]}
          rotation={[-2.104, -1.094, -1.141]}
          scale={[0.88, 0.866, 1.064]}
        />
        <mesh
          name='Caillou3035'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3035.geometry}
          material={materials.Palette}
          position={[2.705, 1.163, 0.049]}
          rotation={[-2.538, 0.801, -2.585]}
          scale={[0.833, 0.72, 0.819]}
        />
        <mesh
          name='Caillou3036'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3036.geometry}
          material={materials.Palette}
          position={[1.353, 1.201, 0.518]}
          rotation={[-2.681, 0.247, -2.275]}
          scale={[0.776, 0.687, 0.727]}
        />
        <mesh
          name='Caillou3037'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3037.geometry}
          material={materials.Palette}
          position={[2.325, 1.163, -0.395]}
          rotation={[-0.64, 0.848, 1.525]}
          scale={[0.833, 0.72, 0.819]}
        />
        <mesh
          name='Cube260'
          castShadow
          receiveShadow
          geometry={nodes.Cube260.geometry}
          material={materials.Palette}
          position={[3.44, 1.063, 4.49]}
          rotation={[-Math.PI, 1.264, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name='Plant1004'
          castShadow
          receiveShadow
          geometry={nodes.Plant1004.geometry}
          material={materials.Palette}
          position={[-2.139, 0.994, 0.084]}
          rotation={[1.813, -0.501, 2.046]}
          scale={0.307}
        />
        <mesh
          name='Plant1005'
          castShadow
          receiveShadow
          geometry={nodes.Plant1005.geometry}
          material={materials.Palette}
          position={[-2.01, 1.003, -0.003]}
          rotation={[2.08, -0.225, 2.762]}
          scale={0.959}
        />
        <mesh
          name='Plant1006'
          castShadow
          receiveShadow
          geometry={nodes.Plant1006.geometry}
          material={materials.Palette}
          position={[-1.666, 1.049, 1.923]}
          rotation={[1.391, -0.525, 1.224]}
          scale={0.307}
        />
        <mesh
          name='Plant1007'
          castShadow
          receiveShadow
          geometry={nodes.Plant1007.geometry}
          material={materials.Palette}
          position={[-1.625, 1.058, 1.773]}
          rotation={[1.817, -0.5, 2.054]}
          scale={0.959}
        />
        <mesh
          name='Plant1008'
          castShadow
          receiveShadow
          geometry={nodes.Plant1008.geometry}
          material={materials.Palette}
          position={[-1.341, 1.049, 1.888]}
          rotation={[2.022, 0.33, -2.553]}
          scale={0.219}
        />
        <mesh
          name='Plant1009'
          castShadow
          receiveShadow
          geometry={nodes.Plant1009.geometry}
          material={materials.Palette}
          position={[-1.303, 1.058, 2.038]}
          rotation={[1.629, 0.55, -1.682]}
          scale={0.959}
        />
        <mesh
          name='Plant1001'
          castShadow
          receiveShadow
          geometry={nodes.Plant1001.geometry}
          material={materials.Palette}
          position={[4.961, 1.049, 4.851]}
          rotation={[1.391, -0.525, 1.224]}
          scale={0.307}
        />
        <mesh
          name='Plant1002'
          castShadow
          receiveShadow
          geometry={nodes.Plant1002.geometry}
          material={materials.Palette}
          position={[5.238, 1.049, 5.123]}
          rotation={[2.113, -0.112, 2.958]}
          scale={0.388}
        />
        <mesh
          name='Plant1003'
          castShadow
          receiveShadow
          geometry={nodes.Plant1003.geometry}
          material={materials.Palette}
          position={[2.795, 1.049, 5.492]}
          rotation={[1.213, 0.43, -0.839]}
          scale={0.307}
        />
        <mesh
          name='Plant1010'
          castShadow
          receiveShadow
          geometry={nodes.Plant1010.geometry}
          material={materials.Palette}
          position={[2.855, 1.049, 5.109]}
          rotation={[1.142, -0.36, 0.657]}
          scale={0.388}
        />
        <mesh
          name='Plant1011'
          castShadow
          receiveShadow
          geometry={nodes.Plant1011.geometry}
          material={materials.Palette}
          position={[2.606, 1.049, 5.273]}
          rotation={[1.029, 0.114, -0.186]}
          scale={0.225}
        />
        <mesh
          name='Plant1012'
          castShadow
          receiveShadow
          geometry={nodes.Plant1012.geometry}
          material={materials.Palette}
          position={[-4.678, 0.908, 5.555]}
          rotation={[1.813, -0.501, 2.046]}
          scale={0.307}
        />
        <mesh
          name='Plant1013'
          castShadow
          receiveShadow
          geometry={nodes.Plant1013.geometry}
          material={materials.Palette}
          position={[-4.55, 0.917, 5.468]}
          rotation={[2.08, -0.225, 2.762]}
          scale={0.959}
        />
        <mesh
          name='Plant1014'
          castShadow
          receiveShadow
          geometry={nodes.Plant1014.geometry}
          material={materials.Palette}
          position={[-3.904, 0.861, 5.827]}
          rotation={[1.915, 0.441, -2.269]}
          scale={0.307}
        />
        <mesh
          name='Plant1015'
          castShadow
          receiveShadow
          geometry={nodes.Plant1015.geometry}
          material={materials.Palette}
          position={[-3.895, 0.871, 5.982]}
          rotation={[1.51, 0.549, -1.455]}
          scale={0.959}
        />
        <mesh
          name='Arbre_1002'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1002.geometry}
          material={materials.Chene_128}
          position={[7.021, 1.928, 3.009]}
          rotation={[-2.94, 0.522, 3.09]}
          scale={[0.748, 0.838, 0.748]}
        />
        <mesh
          name='Arbre_1019'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1019.geometry}
          material={materials.Chene_128}
          position={[7.006, 0.934, 6.757]}
          rotation={[-1.955, -1.534, -1.811]}
          scale={[1.621, 1.815, 1.621]}
        />
        <mesh
          name='Arbre_1011'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1011.geometry}
          material={materials.Chene_128}
          position={[6.546, 1.975, 2.902]}
          rotation={[-0.049, 0.797, 0.179]}
          scale={[1.612, 1.804, 1.612]}
        />
        <mesh
          name='Arbre_1012'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1012.geometry}
          material={materials.Chene_128}
          position={[6.952, 1.903, 3.649]}
          rotation={[0.063, -0.121, 0.11]}
          scale={[1.246, 1.395, 1.246]}
        />
        <mesh
          name='Arbre_1025'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1025.geometry}
          material={materials.Chene_128}
          position={[7.253, 2.038, 3.009]}
          rotation={[-2.879, 1.437, 3.025]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1004'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1004.geometry}
          material={materials.Chene_128}
          position={[8.033, 1.567, -0.51]}
          rotation={[-3.103, -0.438, -2.981]}
          scale={[1.291, 1.446, 1.291]}
        />
        <mesh
          name='Arbre_1006'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1006.geometry}
          material={materials.Chene_128}
          position={[8.509, 1.273, 0.365]}
          rotation={[3.071, 0.479, -3.007]}
          scale={[0.998, 1.118, 0.998]}
        />
        <mesh
          name='Arbre_1007'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1007.geometry}
          material={materials.Chene_128}
          position={[8.775, 1.178, -0.339]}
          rotation={[-2.991, -1.338, -2.851]}
          scale={[0.585, 0.655, 0.585]}
        />
        <mesh
          name='Arbre_1013'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1013.geometry}
          material={materials.Chene_128}
          position={[3.505, 1.403, -6.966]}
          rotation={[-0.046, -0.712, 0.114]}
          scale={[1.239, 1.388, 1.239]}
        />
        <mesh
          name='Arbre_1014'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1014.geometry}
          material={materials.Chene_128}
          position={[2.108, 1.34, -6.907]}
          rotation={[-0.006, 0.382, -0.027]}
          scale={[1.055, 1.181, 1.055]}
        />
        <mesh
          name='Arbre_1015'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1015.geometry}
          material={materials.Chene_128}
          position={[3.379, 1.46, -6.215]}
          rotation={[-0.035, 0.189, 0.151]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1016'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1016.geometry}
          material={materials.Chene_128}
          position={[-5.617, 1.082, 2.617]}
          rotation={[-0.036, 0.302, 0.155]}
          scale={[1.648, 1.845, 1.648]}
        />
        <mesh
          name='Arbre_1017'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1017.geometry}
          material={materials.Chene_128}
          position={[-5.614, 1.077, 3.613]}
          rotation={[0.076, -0.615, 0.146]}
          scale={[1.46, 1.635, 1.46]}
        />
        <mesh
          name='Arbre_1018'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1018.geometry}
          material={materials.Chene_128}
          position={[-5.045, 1.041, 3.121]}
          rotation={[-0.096, 1.202, 0.234]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1009'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1009.geometry}
          material={materials.Chene_128}
          position={[-4.312, 1.466, 8.055]}
          rotation={[-1.741, -1.525, -1.678]}
          scale={[1.46, 1.635, 1.46]}
        />
        <mesh
          name='Arbre_1010'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1010.geometry}
          material={materials.Chene_128}
          position={[-3.578, 1.252, 8.223]}
          rotation={[-0.025, 0.258, 0.079]}
          scale={[0.966, 1.082, 0.966]}
        />
        <mesh
          name='Arbre_1003'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1003.geometry}
          material={materials.Chene_128}
          position={[3.606, 1.085, -3.178]}
          rotation={[3.126, 0.138, -3.102]}
          scale={[1.148, 1.285, 1.148]}
        />
        <group
          name='ClotureMetal_Move'
          position={[1.426, 1.77, -4.619]}
          rotation={[0, 1.09, 0]}
        >
          <mesh
            name='3Piquets_Base'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Base'].geometry}
            material={materials.Palette}
            position={[-1.481, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst001'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst001'].geometry}
            material={materials.Palette}
            position={[-0.939, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst002'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst002'].geometry}
            material={materials.Palette}
            position={[-0.369, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst003'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst003'].geometry}
            material={materials.Palette}
            position={[0.187, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst004'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst004'].geometry}
            material={materials.Palette}
            position={[0.762, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst005'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst005'].geometry}
            material={materials.Palette}
            position={[1.323, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst006'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst006'].geometry}
            material={materials.Palette}
            position={[1.874, -0.606, -1.292]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst007'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst007'].geometry}
            material={materials.Palette}
            position={[-0.939, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst008'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst008'].geometry}
            material={materials.Palette}
            position={[-0.369, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst009'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst009'].geometry}
            material={materials.Palette}
            position={[0.187, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst010'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst010'].geometry}
            material={materials.Palette}
            position={[0.762, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst011'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst011'].geometry}
            material={materials.Palette}
            position={[1.323, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst012'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst012'].geometry}
            material={materials.Palette}
            position={[1.874, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst013'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst013'].geometry}
            material={materials.Palette}
            position={[-1.485, -0.606, 1.307]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst014'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst014'].geometry}
            material={materials.Palette}
            position={[-1.865, -0.606, 1.104]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst015'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst015'].geometry}
            material={materials.Palette}
            position={[-1.865, -0.606, 0.574]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst016'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst016'].geometry}
            material={materials.Palette}
            position={[-1.865, -0.606, -1.109]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst017'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst017'].geometry}
            material={materials.Palette}
            position={[-1.865, -0.606, -0.586]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst018'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst018'].geometry}
            material={materials.Palette}
            position={[2.06, -0.606, 0.9]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst019'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst019'].geometry}
            material={materials.Palette}
            position={[2.06, -0.606, 0.291]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst020'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst020'].geometry}
            material={materials.Palette}
            position={[2.066, -0.606, -0.911]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='3Piquets_Inst021'
            castShadow
            receiveShadow
            geometry={nodes['3Piquets_Inst021'].geometry}
            material={materials.Palette}
            position={[2.066, -0.606, -0.326]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={[1, 1.743, 1]}
          />
          <mesh
            name='Barreaux'
            castShadow
            receiveShadow
            geometry={nodes.Barreaux.geometry}
            material={materials.Palette}
            scale={[1, 1.743, 1]}
          />
        </group>
        <group name='ClotureBois_Move' position={[5.193, 1.707, 5.862]}>
          <mesh
            name='ClotureBois_Base'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Base.geometry}
            material={materials.ClotureBois}
            position={[-2.49, -0.692, -0.933]}
            rotation={[Math.PI, -0.646, Math.PI]}
          />
          <mesh
            name='ClotureBois_Base001'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Base001.geometry}
            material={materials.ClotureBois}
            position={[2.137, -0.692, 1.272]}
            rotation={[0, 0.809, 0]}
          />
          <mesh
            name='ClotureBois_Inst001'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst001.geometry}
            material={materials.ClotureBois}
            position={[-1.191, -0.525, -2.128]}
            rotation={[3.079, -0.752, 2.94]}
          />
          <mesh
            name='ClotureBois_Inst002'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst002.geometry}
            material={materials.ClotureBois}
            position={[-0.678, -0.281, -2.601]}
            rotation={[2.983, -0.725, 2.742]}
          />
          <mesh
            name='ClotureBois_Inst003'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst003.geometry}
            material={materials.ClotureBois}
            position={[-0.056, -0.224, -2.428]}
            rotation={[3.035, 0.79, -3.127]}
          />
          <mesh
            name='ClotureBois_Inst004'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst004.geometry}
            material={materials.ClotureBois}
            position={[0.605, -0.215, -1.7]}
            rotation={[3.044, 0.879, -2.99]}
          />
          <mesh
            name='ClotureBois_Inst005'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst005.geometry}
            material={materials.ClotureBois}
            position={[1.202, -0.407, -0.944]}
            rotation={[3.044, 0.879, -2.817]}
          />
          <mesh
            name='ClotureBois_Inst006'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst006.geometry}
            material={materials.ClotureBois}
            position={[1.884, -0.603, -0.153]}
            rotation={[3.051, 0.815, -3]}
          />
          <mesh
            name='ClotureBois_Inst007'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst007.geometry}
            material={materials.ClotureBois}
            position={[2.315, -0.656, 0.444]}
            rotation={[2.943, 1.249, -2.877]}
          />
          <mesh
            name='ClotureBois_Inst008'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst008.geometry}
            material={materials.ClotureBois}
            position={[1.455, -0.689, 1.968]}
            rotation={[0.064, 0.759, -0.063]}
          />
          <mesh
            name='ClotureBois_Inst009'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst009.geometry}
            material={materials.ClotureBois}
            position={[0.719, -0.612, 2.655]}
            rotation={[0.177, 0.794, -0.229]}
          />
          <mesh
            name='ClotureBois_Inst010'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst010.geometry}
            material={materials.ClotureBois}
            position={[0.109, -0.536, 2.52]}
            rotation={[3.051, 0.815, -3]}
          />
          <mesh
            name='ClotureBois_Inst011'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst011.geometry}
            material={materials.ClotureBois}
            position={[-0.546, -0.536, 1.81]}
            rotation={[3.051, 0.815, -3.128]}
          />
          <mesh
            name='ClotureBois_Inst012'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst012.geometry}
            material={materials.ClotureBois}
            position={[-1.214, -0.618, 1.101]}
            rotation={[3.051, 0.815, -3.136]}
          />
          <mesh
            name='ClotureBois_Inst013'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst013.geometry}
            material={materials.ClotureBois}
            position={[-1.91, -0.663, 0.35]}
            rotation={[3.051, 0.815, -3.078]}
          />
          <mesh
            name='ClotureBois_Inst014'
            castShadow
            receiveShadow
            geometry={nodes.ClotureBois_Inst014.geometry}
            material={materials.ClotureBois}
            position={[-2.538, -0.708, -0.332]}
            rotation={[3.051, 0.815, -3.076]}
          />
        </group>
        <mesh
          name='Land'
          castShadow
          receiveShadow
          geometry={nodes.Land.geometry}
          material={materials.Ground}
        />
        <mesh
          name='SousSol'
          castShadow
          receiveShadow
          geometry={nodes.SousSol.geometry}
          material={materials.Palette}
        />
        <group name='Lampadaires_1' position={[-2.358, 1.346, -0.099]}>
          <mesh
            name='Cylinder026'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder026_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group
          name='Lampadaires_1001'
          position={[-2.166, 1.183, 1.725]}
          rotation={[-1.538, -1.477, -1.706]}
          scale={0.668}
        >
          <mesh
            name='Cylinder026'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder026_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <mesh
          name='Pin_Base'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Base.geometry}
          material={materials.Pin_128_Inst}
          position={[-6.274, 1.084, -0.395]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.293, 0.567, 0.293]}
        />
        <mesh
          name='Pin_Inst001'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst001.geometry}
          material={materials.Pin_128_Inst}
          position={[-6.61, 1.084, -1.966]}
          rotation={[0, -1.152, 0]}
          scale={[0.171, 0.331, 0.171]}
        />
        <mesh
          name='Pin_Inst002'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst002.geometry}
          material={materials.Pin_128_Inst}
          position={[-5.433, 1.084, -0.975]}
          rotation={[Math.PI, -1.44, Math.PI]}
          scale={[0.219, 0.423, 0.219]}
        />
        <mesh
          name='Pin_Inst003'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst003.geometry}
          material={materials.Pin_128_Inst}
          position={[-3.731, 1.084, -4.77]}
          rotation={[0.05, -0.962, -0.018]}
          scale={[0.219, 0.423, 0.219]}
        />
        <mesh
          name='Pin_Inst004'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst004.geometry}
          material={materials.Pin_128_Inst}
          position={[-4.815, 1.732, -5.331]}
          rotation={[0.056, -0.637, -0.08]}
          scale={[0.248, 0.48, 0.248]}
        />
        <mesh
          name='Pin_Inst005'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst005.geometry}
          material={materials.Pin_128_Inst}
          position={[-3.338, 1.439, -5.855]}
          rotation={[Math.PI, -1.361, Math.PI]}
          scale={[0.193, 0.374, 0.193]}
        />
        <mesh
          name='Pin_Inst006'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst006.geometry}
          material={materials.Pin_128_Inst}
          position={[-2.385, 1.421, -6.565]}
          rotation={[0, -1.177, 0]}
          scale={[0.226, 0.437, 0.226]}
        />
        <mesh
          name='Pin_Inst007'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst007.geometry}
          material={materials.Pin_128_Inst}
          position={[3.187, 1.359, -4.864]}
          rotation={[0.112, -1.313, 0.049]}
          scale={[0.219, 0.423, 0.219]}
        />
        <mesh
          name='Pin_Inst008'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst008.geometry}
          material={materials.Pin_128_Inst}
          position={[4.283, 1.647, -5.47]}
          rotation={[2.721, -1.17, 2.634]}
          scale={[0.251, 0.485, 0.251]}
        />
        <mesh
          name='Pin_Inst009'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst009.geometry}
          material={materials.Pin_128_Inst}
          position={[4.724, 1.765, -3.976]}
          rotation={[0.362, -1.302, 0.312]}
          scale={[0.217, 0.42, 0.217]}
        />
        <mesh
          name='Pin_Inst010'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst010.geometry}
          material={materials.Pin_128_Inst}
          position={[5.23, 1.765, -2.951]}
          rotation={[0.013, 0.114, 0.002]}
          scale={[0.192, 0.372, 0.192]}
        />
        <mesh
          name='Pin_Inst011'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst011.geometry}
          material={materials.Pin_128_Inst}
          position={[7.254, 1.765, -2.107]}
          rotation={[0.013, -0.233, 0.006]}
          scale={[0.212, 0.41, 0.212]}
        />
        <mesh
          name='Pin_Inst012'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst012.geometry}
          material={materials.Pin_128_Inst}
          position={[0.836, 1.149, 3.974]}
          rotation={[0.024, -1.029, 0.024]}
          scale={[0.221, 0.427, 0.221]}
        />
        <mesh
          name='Pin_Inst013'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst013.geometry}
          material={materials.Pin_128_Inst}
          position={[1.784, 1.149, 5.194]}
          rotation={[0.014, -0.49, 0.01]}
          scale={[0.221, 0.427, 0.221]}
        />
        <mesh
          name='Pin_Inst014'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst014.geometry}
          material={materials.Pin_128_Inst}
          position={[1.473, 1.443, 6.792]}
          rotation={[3.128, -0.448, 3.139]}
          scale={[0.171, 0.33, 0.171]}
        />
        <mesh
          name='Pin_Inst015'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst015.geometry}
          material={materials.Pin_128_Inst}
          position={[3.563, 1.374, 7.765]}
          rotation={[3.122, 0.87, -3.124]}
          scale={[0.243, 0.47, 0.243]}
        />
        <mesh
          name='Pin_Inst016'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst016.geometry}
          material={materials.Pin_128_Inst}
          position={[3.693, 0.939, 6.456]}
          rotation={[0.02, -0.894, 0.019]}
          scale={[0.161, 0.312, 0.161]}
        />
        <mesh
          name='Pin_Inst017'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst017.geometry}
          material={materials.Pin_128_Inst}
          position={[8.666, 0.939, 6.222]}
          rotation={[3.095, -1.297, 3.1]}
          scale={[0.228, 0.441, 0.228]}
        />
        <mesh
          name='Pin_Inst018'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst018.geometry}
          material={materials.Pin_128_Inst}
          position={[6.758, 0.939, 8.534]}
          rotation={[0.022, 0.961, -0.015]}
          scale={[0.228, 0.441, 0.228]}
        />
        <mesh
          name='Pin_Inst019'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst019.geometry}
          material={materials.Pin_128_Inst}
          position={[8.251, 1.151, 8.235]}
          rotation={[0.013, 0.233, 0]}
          scale={[0.162, 0.313, 0.162]}
        />
        <mesh
          name='Pin_Inst020'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst020.geometry}
          material={materials.Pin_128_Inst}
          position={[-2.121, 1.194, 6.12]}
          rotation={[-3.11, 0.355, 3.022]}
          scale={[0.243, 0.47, 0.243]}
        />
        <mesh
          name='Pin_Inst021'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst021.geometry}
          material={materials.Pin_128_Inst}
          position={[-3.654, 0.908, 6.569]}
          rotation={[3.101, 1.254, -3.1]}
          scale={[0.208, 0.403, 0.208]}
        />
        <mesh
          name='Pin_Inst022'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst022.geometry}
          material={materials.Pin_128_Inst}
          position={[-4.664, 1.059, 6.644]}
          rotation={[3.126, 0.644, -3.129]}
          scale={[0.165, 0.32, 0.165]}
        />
        <mesh
          name='Pin_Inst023'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst023.geometry}
          material={materials.Pin_128_Inst}
          position={[-5.187, 0.953, 5.522]}
          rotation={[0.022, 0.962, -0.015]}
          scale={[0.23, 0.444, 0.23]}
        />
        <mesh
          name='Pin_Inst024'
          castShadow
          receiveShadow
          geometry={nodes.Pin_Inst024.geometry}
          material={materials.Pin_128_Inst}
          position={[-1.159, 1.104, -5.231]}
          rotation={[Math.PI, -1.268, Math.PI]}
          scale={[0.102, 0.197, 0.102]}
        />
        <group name='Peuplier' position={[-1.075, 1.035, -3.094]} scale={0.167}>
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere001'
          position={[-0.909, 1.035, -2.686]}
          rotation={[Math.PI, -1.412, Math.PI]}
          scale={0.193}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere002'
          position={[-0.692, 1.035, -2.227]}
          rotation={[0, -0.673, 0]}
          scale={0.167}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere003'
          position={[-4.232, 0.942, -1.341]}
          rotation={[-Math.PI, 0.514, -Math.PI]}
          scale={0.177}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere004'
          position={[-4.176, 0.942, -1.778]}
          rotation={[0, 0.897, 0]}
          scale={0.152}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere005'
          position={[-4.138, 0.942, -2.285]}
          rotation={[-Math.PI, 1.187, -Math.PI]}
          scale={0.167}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere006'
          position={[0.323, 1.361, -6.038]}
          rotation={[0, 0.897, 0]}
          scale={0.201}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere007'
          position={[2.032, 1.071, 0.426]}
          rotation={[-Math.PI, 1.187, -Math.PI]}
          scale={0.268}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere008'
          position={[1.45, 1.071, 0.303]}
          rotation={[-Math.PI, 0.227, -Math.PI]}
          scale={0.196}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere009'
          position={[2.414, 1.071, -0.217]}
          rotation={[-Math.PI, 1.007, -Math.PI]}
          scale={0.217}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin_128}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <mesh
          name='Arbre_1033'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1033.geometry}
          material={materials.Chene_128}
          position={[-4.768, 1.381, 9.362]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1008'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1008.geometry}
          material={materials.Chene_128}
          position={[1.191, 1.381, 7.856]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1020'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1020.geometry}
          material={materials.Chene_128}
          position={[-3.886, 1.087, 2.585]}
          rotation={[-0.097, 0.34, 0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1026'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1026.geometry}
          material={materials.Chene_128}
          position={[-5.04, 0.905, -3.386]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1030'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1030.geometry}
          material={materials.Chene_128}
          position={[3.763, 1.212, 3.526]}
          rotation={[-0.097, 0.34, 0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1031'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1031.geometry}
          material={materials.Chene_128}
          position={[4.167, 1.319, 3.228]}
          rotation={[-0.098, -0.36, -0.029]}
          scale={0.508}
        />
        <mesh
          name='Arbre_1027'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1027.geometry}
          material={materials.Chene_128}
          position={[1.98, 1.142, -0.212]}
          rotation={[-3.048, -0.185, -3.118]}
          scale={0.492}
        />
        <mesh
          name='Arbre_1028'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1028.geometry}
          material={materials.Chene_128}
          position={[1.622, 1.166, -0.025]}
          rotation={[-3.036, 0.514, 3.096]}
          scale={0.409}
        />
        <mesh
          name='Arbre_1029'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1029.geometry}
          material={materials.Chene_128}
          position={[1.915, 1.142, 0.072]}
          rotation={[-0.095, 0.264, 0.031]}
          scale={0.3}
        />
        <mesh
          name='Arbre_1021'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1021.geometry}
          material={materials.Chene_128}
          position={[2.701, 0.992, -3.937]}
          rotation={[-3.032, 0.571, 3.088]}
          scale={0.671}
        />
        <mesh
          name='Arbre_1001'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1001.geometry}
          material={materials.Chene_128}
          position={[-0.048, 1.153, -5.599]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1005'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1005.geometry}
          material={materials.Chene_128}
          position={[0.022, 1.153, -5.165]}
          rotation={[-0.149, 0.904, 0.123]}
          scale={0.396}
        />
        <mesh
          name='Arbre_1022'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1022.geometry}
          material={materials.Chene_128}
          position={[4.753, 1.44, 3.341]}
          rotation={[-2.918, -0.944, -2.944]}
          scale={0.533}
        />
        <mesh
          name='Arbre_1023'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1023.geometry}
          material={materials.Chene_128}
          position={[4.62, 1.323, 3.759]}
          rotation={[-3.022, -0.25, -3.074]}
          scale={0.444}
        />
        <mesh
          name='Arbre_1024'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1024.geometry}
          material={materials.Chene_128}
          position={[4.917, 1.43, 3.611]}
          rotation={[-0.103, 1.034, 0.088]}
          scale={0.325}
        />
        <mesh
          name='Arbre_1032'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1032.geometry}
          material={materials.Chene_128}
          position={[6.647, 0.908, 6.679]}
          rotation={[-0.32, -1.275, -0.301]}
          scale={0.41}
        />
        <mesh
          name='Arbre_1034'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1034.geometry}
          material={materials.Chene_128}
          position={[6.647, 0.908, 6.253]}
          rotation={[-0.105, -0.512, -0.046]}
          scale={0.61}
        />
        <mesh
          name='Arbre_1035'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1035.geometry}
          material={materials.Chene_128}
          position={[3.788, 1.212, 3.165]}
          rotation={[-3.041, -0.418, -3.095]}
          scale={0.372}
        />
        <group name='Lampadaire_2001' position={[3.458, 1.108, 4.046]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2002' position={[-0.178, 1.122, -3.173]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2003' position={[1.018, 1.199, -2.521]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2004' position={[4.572, 1.516, -0.864]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2005' position={[4.558, 1.467, -1.374]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <mesh
          name='ArbreMort_1'
          castShadow
          receiveShadow
          geometry={nodes.ArbreMort_1.geometry}
          material={materials.Palette}
          position={[6.335, 3.046, 0.546]}
        />
        <mesh
          name='ArbreMort_1001'
          castShadow
          receiveShadow
          geometry={nodes.ArbreMort_1001.geometry}
          material={materials.Palette}
          position={[6.547, 2.649, -2.656]}
          rotation={[1.386, 1.436, -1.248]}
          scale={0.611}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/game/Land.glb');
