/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { dir } from 'console';

export function Land(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Land_1_01_Anim.glb', true);
  const { actions, mixer } = useAnimations(animations, group);
  useEffect(() => {
    console.log(dir(actions));
    actions.KeyAction.play();
  }, [mixer]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='Terrain3'
          castShadow
          receiveShadow
          geometry={nodes.Terrain3.geometry}
          material={materials.Ground}
        />
        <group name='Cylinder' position={[3.837, 1.016, -3.726]} scale={0.11}>
          <mesh
            name='Cylinder_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder001'
          position={[5.825, 2.382, -5.757]}
          scale={0.138}
        >
          <mesh
            name='Cylinder001_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder001_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder002'
          position={[5.418, 2.12, -6.536]}
          scale={0.138}
        >
          <mesh
            name='Cylinder002_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder002_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder003'
          position={[7.518, 1.406, -7.687]}
          scale={0.138}
        >
          <mesh
            name='Cylinder003_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder003_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group name='Cylinder004' position={[5.57, 2.382, -5.026]} scale={0.11}>
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder004_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder005'
          position={[-6.024, 0.934, 1.476]}
          scale={0.11}
        >
          <mesh
            name='Cylinder005_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder005_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder006'
          position={[-8.466, 0.964, 1.05]}
          scale={0.138}
        >
          <mesh
            name='Cylinder006_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder006_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder007'
          position={[-7.271, 0.888, 5.865]}
          scale={0.11}
        >
          <mesh
            name='Cylinder007_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder007_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder007_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group name='Cylinder008' position={[-6.62, 0.834, 6.406]} scale={0.11}>
          <mesh
            name='Cylinder008_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder008_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder008_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder009'
          position={[-7.653, 0.921, 6.603]}
          scale={0.138}
        >
          <mesh
            name='Cylinder009_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder009_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder009_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder010'
          position={[-7.89, 0.768, 5.621]}
          scale={0.138}
        >
          <mesh
            name='Cylinder010_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder010_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group name='Cylinder011' position={[5.52, 0.907, 7.182]} scale={0.138}>
          <mesh
            name='Cylinder011_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder011_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder012'
          position={[5.861, 0.757, 5.914]}
          scale={0.138}
        >
          <mesh
            name='Cylinder012_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder012_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder012_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder013'
          position={[6.446, 0.894, 6.938]}
          scale={0.138}
        >
          <mesh
            name='Cylinder013_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder013_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder013_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group name='Cylinder014' position={[6.95, 1.288, 5.147]} scale={0.11}>
          <mesh
            name='Cylinder014_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder014_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder014_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder015'
          position={[9.275, 0.892, 4.939]}
          scale={0.138}
        >
          <mesh
            name='Cylinder015_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder015_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder015_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder015_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder016'
          position={[8.104, 0.922, 5.085]}
          scale={0.138}
        >
          <mesh
            name='Cylinder016_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder016_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder016_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder016_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder017'
          position={[-2.193, 1.016, -5.115]}
          scale={0.11}
        >
          <mesh
            name='Cylinder017_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder017_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder017_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder018'
          position={[-1.899, 0.838, -4.425]}
          scale={0.076}
        >
          <mesh
            name='Cylinder018_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder018_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder018_2.geometry}
            material={materials.Pins}
          />
        </group>
        <group
          name='Cylinder019'
          position={[-1.415, 0.933, -4.792]}
          scale={0.1}
        >
          <mesh
            name='Cylinder019_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder019_1.geometry}
            material={materials.Tronc}
          />
          <mesh
            name='Cylinder019_2'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder019_2.geometry}
            material={materials.Pins}
          />
        </group>
        <mesh
          name='Icosphere'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials.Rock1}
          position={[-3.419, 0.987, 0.095]}
          rotation={[0, 0.474, 0]}
          scale={[0.777, 0.261, 0.396]}
        />
        <mesh
          name='Icosphere001'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001.geometry}
          material={materials.Rock1}
          position={[-3.16, 0.961, -0.564]}
          rotation={[-0.038, 0.1, -0.295]}
          scale={[0.497, 0.167, 0.253]}
        />
        <mesh
          name='Icosphere002'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere002.geometry}
          material={materials.Rock1}
          position={[-6.112, 0.987, 5.264]}
          rotation={[0, -1.209, 0]}
          scale={[0.777, 0.261, 0.396]}
        />
        <mesh
          name='Icosphere003'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={materials.Rock1}
          position={[-5.485, 1.013, 5.595]}
          rotation={[-1.869, -1.532, -2.168]}
          scale={[0.271, 0.167, 0.253]}
        />
        <mesh
          name='Icosphere004'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials.Rock1}
          position={[-6.602, 0.905, 5.673]}
          rotation={[-3.034, -1.212, 2.943]}
          scale={[0.413, 0.139, 0.349]}
        />
        <mesh
          name='Icosphere005'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere005.geometry}
          material={materials.Rock1}
          position={[-8.287, 1.069, 7.3]}
          rotation={[-1.869, -1.532, -2.168]}
          scale={[0.166, 0.102, 0.155]}
        />
        <mesh
          name='Icosphere006'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere006.geometry}
          material={materials.Rock1}
          position={[-8.131, 1.069, 7.045]}
          rotation={[-1.869, -1.532, -2.168]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere007'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere007.geometry}
          material={materials.Rock1}
          position={[-8.052, 1.033, 7.398]}
          rotation={[-0.088, -1.13, -0.378]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere008'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere008.geometry}
          material={materials.Rock1}
          position={[7.127, 1.997, -6.475]}
          rotation={[2.877, -0.516, -2.896]}
          scale={[0.777, 0.261, 0.396]}
        />
        <mesh
          name='Icosphere009'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere009.geometry}
          material={materials.Rock1}
          position={[6.621, 2.37, -6.084]}
          rotation={[2.996, -0.067, 1.468]}
          scale={[0.553, 0.203, 0.308]}
        />
        <mesh
          name='Icosphere010'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere010.geometry}
          material={materials.Rock1}
          position={[6.642, 2.075, -6.89]}
          rotation={[-3.103, 0.189, 2.836]}
          scale={[0.413, 0.139, 0.211]}
        />
        <mesh
          name='Icosphere011'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere011.geometry}
          material={materials.Rock1}
          position={[6.626, 1.069, 7.787]}
          rotation={[-1.869, -1.532, -2.168]}
          scale={[0.166, 0.102, 0.155]}
        />
        <mesh
          name='Icosphere012'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere012.geometry}
          material={materials.Rock1}
          position={[6.783, 1.069, 7.533]}
          rotation={[-1.869, -1.532, -2.168]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere013'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere013.geometry}
          material={materials.Rock1}
          position={[6.861, 1.033, 7.885]}
          rotation={[-0.088, -1.13, -0.378]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere014'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere014.geometry}
          material={materials.Rock1}
          position={[7.419, 1.069, 6.807]}
          rotation={[-3.087, -0.817, 2.883]}
          scale={[0.166, 0.102, 0.155]}
        />
        <mesh
          name='Icosphere015'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere015.geometry}
          material={materials.Rock1}
          position={[7.707, 1.069, 6.725]}
          rotation={[-3.087, -0.817, 2.883]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere016'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere016.geometry}
          material={materials.Rock1}
          position={[7.526, 1.033, 7.038]}
          rotation={[-3.016, -1.267, 2.963]}
          scale={[0.135, 0.083, 0.126]}
        />
        <mesh
          name='Icosphere017'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere017.geometry}
          material={materials.Rock1}
          position={[7.322, 1.069, 7.363]}
          rotation={[-0.039, -0.239, -0.308]}
          scale={[0.541, 0.195, 0.296]}
        />
        <mesh
          name='Plane'
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.Water}
          position={[-3.295, 0.845, -3.341]}
        />
        <mesh
          name='Crane'
          castShadow
          receiveShadow
          geometry={nodes.Crane.geometry}
          material={materials.Rock2}
          morphTargetDictionary={nodes.Crane.morphTargetDictionary}
          morphTargetInfluences={nodes.Crane.morphTargetInfluences}
          position={[6.895, 3.775, 3.121]}
          rotation={[-Math.PI / 2, -1.322, -Math.PI / 2]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/game/Land_1_01_Anim.glb');
