/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Land(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Land.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <mesh
          name='LP_Grave_1001'
          castShadow
          receiveShadow
          geometry={nodes.LP_Grave_1001.geometry}
          material={materials.Palette}
          position={[1.509, 1.249, -2.865]}
          rotation={[0.076, -0.55, -0.143]}
          scale={0.913}
        />
        <group
          name='Caveau'
          position={[-4.295, 1.08, 5.923]}
          rotation={[Math.PI, -0.971, Math.PI]}
        >
          <mesh
            name='Cube007_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cube007_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_2.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <mesh
          name='Fantom_1'
          castShadow
          receiveShadow
          geometry={nodes.Fantom_1.geometry}
          material={materials.Palette}
          position={[-4.522, 1.271, 5.945]}
          rotation={[3.085, 0.691, -2.992]}
        />
        <mesh
          name='Fantom_2'
          castShadow
          receiveShadow
          geometry={nodes.Fantom_2.geometry}
          material={materials.Palette}
          position={[2.706, 1.554, -3.917]}
          rotation={[-0.016, 0.214, 0.019]}
        />
        <mesh
          name='Caillou1'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1.geometry}
          material={materials.Palette}
          position={[4.237, 1.105, 5.867]}
          rotation={[3.083, -0.213, -2.295]}
          scale={0.2}
        />
        <mesh
          name='Caillou2'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2.geometry}
          material={materials.Palette}
          position={[4.391, 1.117, 5.991]}
          rotation={[0.231, 0.865, 0.644]}
          scale={0.2}
        />
        <mesh
          name='Caillou3'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3.geometry}
          material={materials.Palette}
          position={[4.368, 1.088, 6.148]}
          rotation={[-0.474, 0.465, 1.15]}
          scale={0.2}
        />
        <mesh
          name='Caillou1002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1002.geometry}
          material={materials.Palette}
          position={[5.272, 1.105, 5.348]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.2}
        />
        <mesh
          name='Caillou2002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2002.geometry}
          material={materials.Palette}
          position={[5.118, 1.117, 5.223]}
          rotation={[2.911, -0.863, -2.497]}
          scale={0.2}
        />
        <mesh
          name='Caillou3002'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3002.geometry}
          material={materials.Palette}
          position={[5.141, 1.088, 5.067]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.2}
        />
        <mesh
          name='Caillou1004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1004.geometry}
          material={materials.Palette}
          position={[3.157, 1.161, -4.188]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.57}
        />
        <mesh
          name='Caillou2004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2004.geometry}
          material={materials.Palette}
          position={[2.932, 1.405, -4.553]}
          rotation={[-1.123, -0.71, -2.246]}
          scale={0.51}
        />
        <mesh
          name='Caillou3005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3005.geometry}
          material={materials.Palette}
          position={[2.892, 1.247, -4.378]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.956}
        />
        <mesh
          name='Caillou1005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1005.geometry}
          material={materials.Palette}
          position={[-4.723, 1.07, -3.368]}
          rotation={[0.305, 0.184, 0.813]}
          scale={0.57}
        />
        <mesh
          name='Caillou2005'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2005.geometry}
          material={materials.Palette}
          position={[-4.948, 1.131, -3.734]}
          rotation={[-1.123, -0.71, -2.246]}
          scale={0.51}
        />
        <mesh
          name='Caillou1007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1007.geometry}
          material={materials.Palette}
          position={[-4.327, 1.482, 9.163]}
          rotation={[0.058, 0.211, 0.846]}
          scale={0.57}
        />
        <mesh
          name='Caillou2006'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2006.geometry}
          material={materials.Palette}
          position={[-4.976, 1.64, 8.757]}
          rotation={[-0.701, -1.127, -1.646]}
          scale={0.51}
        />
        <mesh
          name='Caillou3006'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3006.geometry}
          material={materials.Palette}
          position={[-4.556, 1.639, 8.978]}
          rotation={[-2.668, -0.463, -1.993]}
          scale={0.956}
        />
        <mesh
          name='Caillou3007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3007.geometry}
          material={materials.Palette}
          position={[0.89, 1.447, 7.632]}
          rotation={[-3.085, -0.647, -2.752]}
          scale={0.597}
        />
        <mesh
          name='Caillou1008'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1008.geometry}
          material={materials.Palette}
          position={[0.912, 1.381, 8.048]}
          rotation={[0.058, -0.178, 0.869]}
          scale={0.57}
        />
        <mesh
          name='Caillou1009'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1009.geometry}
          material={materials.Palette}
          position={[0.04, 1.137, 0.071]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.616}
        />
        <mesh
          name='Caillou1006'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1006.geometry}
          material={materials.Palette}
          position={[1.972, 1.205, 0.139]}
          rotation={[0, -0.306, 0]}
          scale={0.795}
        />
        <mesh
          name='Caillou1010'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1010.geometry}
          material={materials.Palette}
          position={[4.455, 1.482, 0.24]}
          rotation={[3.085, -0.064, -2.287]}
          scale={0.57}
        />
        <mesh
          name='Caillou2007'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2007.geometry}
          material={materials.Palette}
          position={[4.055, 1.375, 0.396]}
          rotation={[-2.179, 1.227, 1.213]}
          scale={0.51}
        />
        <mesh
          name='Caillou3008'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3008.geometry}
          material={materials.Palette}
          position={[4.252, 1.452, 0.632]}
          rotation={[-0.531, 0.274, 1.42]}
          scale={0.956}
        />
        <mesh
          name='Caillou1001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1001.geometry}
          material={materials.Palette}
          position={[-1.514, 1.004, 1.729]}
          rotation={[-0.133, -0.133, 0.016]}
        />
        <mesh
          name='Caillou1003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou1003.geometry}
          material={materials.Palette}
          position={[-1.724, 1.022, 1.762]}
          rotation={[-0.109, -1.023, 0.031]}
          scale={[0.839, 0.839, 0.639]}
        />
        <mesh
          name='Caillou2001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2001.geometry}
          material={materials.Palette}
          position={[-1.28, 1.002, 1.847]}
          rotation={[-0.214, -0.078, -0.089]}
        />
        <mesh
          name='Caillou2003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou2003.geometry}
          material={materials.Palette}
          position={[-1.263, 1.043, 2.129]}
          rotation={[-0.287, 1.465, 0.153]}
          scale={1.308}
        />
        <mesh
          name='Caillou3001'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3001.geometry}
          material={materials.Palette}
          position={[-1.448, 1.047, 2.03]}
          rotation={[-0.133, -0.133, 0.016]}
          scale={[0.91, 1.467, 1.467]}
        />
        <mesh
          name='Caillou3003'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3003.geometry}
          material={materials.Palette}
          position={[-1.591, 1.049, 1.939]}
          rotation={[-0.159, 0.981, 0.029]}
        />
        <mesh
          name='Caillou3004'
          castShadow
          receiveShadow
          geometry={nodes.Caillou3004.geometry}
          material={materials.Palette}
          position={[-1.557, 1.046, 2.053]}
          rotation={[-0.159, 0.981, 0.029]}
          scale={[1.089, 1, 1.331]}
        />
        <mesh
          name='Pin002'
          castShadow
          receiveShadow
          geometry={nodes.Pin002.geometry}
          material={materials.Pin512}
          position={[1.412, 1.389, 6.752]}
          rotation={[0, -1.391, 0]}
          scale={[0.162, 0.313, 0.162]}
        />
        <mesh
          name='Pin030'
          castShadow
          receiveShadow
          geometry={nodes.Pin030.geometry}
          material={materials.Pin512}
          position={[3.508, 1.389, 7.73]}
          rotation={[0, -0.275, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin031'
          castShadow
          receiveShadow
          geometry={nodes.Pin031.geometry}
          material={materials.Pin512}
          position={[3.648, 0.942, 6.472]}
          rotation={[0, -1.027, 0]}
          scale={[0.157, 0.303, 0.157]}
        />
        <mesh
          name='Pin032'
          castShadow
          receiveShadow
          geometry={nodes.Pin032.geometry}
          material={materials.Pin512}
          position={[6.782, 1.059, 8.489]}
          rotation={[0, -0.174, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin033'
          castShadow
          receiveShadow
          geometry={nodes.Pin033.geometry}
          material={materials.Pin512}
          position={[8.24, 1.14, 8.189]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.179, 0.346, 0.179]}
        />
        <mesh
          name='Pin034'
          castShadow
          receiveShadow
          geometry={nodes.Pin034.geometry}
          material={materials.Pin512}
          position={[8.639, 0.956, 6.233]}
          rotation={[0, -0.837, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin035'
          castShadow
          receiveShadow
          geometry={nodes.Pin035.geometry}
          material={materials.Pin512}
          position={[1.831, 0.988, 5.135]}
          rotation={[Math.PI, -0.446, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin036'
          castShadow
          receiveShadow
          geometry={nodes.Pin036.geometry}
          material={materials.Pin512}
          position={[0.793, 1.094, 3.957]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin037'
          castShadow
          receiveShadow
          geometry={nodes.Pin037.geometry}
          material={materials.Pin512}
          position={[-2.141, 0.988, 6.153]}
          rotation={[Math.PI, -0.446, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin038'
          castShadow
          receiveShadow
          geometry={nodes.Pin038.geometry}
          material={materials.Pin512}
          position={[-3.599, 0.841, 6.552]}
          rotation={[0, -1.031, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin039'
          castShadow
          receiveShadow
          geometry={nodes.Pin039.geometry}
          material={materials.Pin512}
          position={[-4.657, 1.089, 6.612]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.163, 0.315, 0.163]}
        />
        <mesh
          name='Pin040'
          castShadow
          receiveShadow
          geometry={nodes.Pin040.geometry}
          material={materials.Pin512}
          position={[-5.256, 0.988, 5.534]}
          rotation={[0, -0.275, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin041'
          castShadow
          receiveShadow
          geometry={nodes.Pin041.geometry}
          material={materials.Pin512}
          position={[-6.274, 1.084, -0.395]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.293, 0.567, 0.293]}
        />
        <mesh
          name='Pin042'
          castShadow
          receiveShadow
          geometry={nodes.Pin042.geometry}
          material={materials.Pin512}
          position={[-5.464, 0.985, -1.019]}
          rotation={[0, -0.275, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin043'
          castShadow
          receiveShadow
          geometry={nodes.Pin043.geometry}
          material={materials.Pin512}
          position={[7.201, 1.389, -2.172]}
          rotation={[0, -1.223, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin044'
          castShadow
          receiveShadow
          geometry={nodes.Pin044.geometry}
          material={materials.Pin512}
          position={[5.225, 1.627, -3.01]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin045'
          castShadow
          receiveShadow
          geometry={nodes.Pin045.geometry}
          material={materials.Pin512}
          position={[4.686, 1.707, -3.968]}
          rotation={[0, -0.275, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin046'
          castShadow
          receiveShadow
          geometry={nodes.Pin046.geometry}
          material={materials.Pin512}
          position={[4.327, 1.943, -5.446]}
          rotation={[0, -0.415, 0]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin047'
          castShadow
          receiveShadow
          geometry={nodes.Pin047.geometry}
          material={materials.Pin512}
          position={[3.149, 1.389, -4.827]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin049'
          castShadow
          receiveShadow
          geometry={nodes.Pin049.geometry}
          material={materials.Pin512}
          position={[-2.401, 1.389, -6.564]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin050'
          castShadow
          receiveShadow
          geometry={nodes.Pin050.geometry}
          material={materials.Pin512}
          position={[-3.419, 1.389, -5.865]}
          rotation={[0, -0.275, 0]}
          scale={[0.168, 0.325, 0.168]}
        />
        <mesh
          name='Pin051'
          castShadow
          receiveShadow
          geometry={nodes.Pin051.geometry}
          material={materials.Pin512}
          position={[-3.699, 1.217, -4.807]}
          rotation={[Math.PI, -0.446, Math.PI]}
          scale={[0.279, 0.54, 0.279]}
        />
        <mesh
          name='Pin052'
          castShadow
          receiveShadow
          geometry={nodes.Pin052.geometry}
          material={materials.Pin512}
          position={[-4.817, 1.389, -5.406]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.229, 0.442, 0.229]}
        />
        <mesh
          name='Pin053'
          castShadow
          receiveShadow
          geometry={nodes.Pin053.geometry}
          material={materials.Pin512}
          position={[-1.183, 1.05, -5.286]}
          rotation={[Math.PI, -1.202, Math.PI]}
          scale={[0.096, 0.185, 0.096]}
        />
        <mesh
          name='Pin001'
          castShadow
          receiveShadow
          geometry={nodes.Pin001.geometry}
          material={materials.Pin512}
          position={[-6.58, 1.243, -1.879]}
          rotation={[0, 0.155, 0]}
          scale={[0.179, 0.346, 0.179]}
        />
        <mesh
          name='Cube260'
          castShadow
          receiveShadow
          geometry={nodes.Cube260.geometry}
          material={materials.Palette}
          position={[3.44, 1.063, 4.49]}
          rotation={[-Math.PI, 1.264, -Math.PI]}
          scale={0.25}
        />
        <mesh
          name='Plant1004'
          castShadow
          receiveShadow
          geometry={nodes.Plant1004.geometry}
          material={materials.Palette}
          position={[-2.139, 0.994, 0.084]}
          rotation={[1.813, -0.501, 2.046]}
          scale={0.307}
        />
        <mesh
          name='Plant1005'
          castShadow
          receiveShadow
          geometry={nodes.Plant1005.geometry}
          material={materials.Palette}
          position={[-2.01, 1.003, -0.003]}
          rotation={[2.08, -0.225, 2.762]}
          scale={0.959}
        />
        <mesh
          name='Plant1006'
          castShadow
          receiveShadow
          geometry={nodes.Plant1006.geometry}
          material={materials.Palette}
          position={[-1.666, 1.049, 1.923]}
          rotation={[1.391, -0.525, 1.224]}
          scale={0.307}
        />
        <mesh
          name='Plant1007'
          castShadow
          receiveShadow
          geometry={nodes.Plant1007.geometry}
          material={materials.Palette}
          position={[-1.625, 1.058, 1.773]}
          rotation={[1.817, -0.5, 2.054]}
          scale={0.959}
        />
        <mesh
          name='Plant1008'
          castShadow
          receiveShadow
          geometry={nodes.Plant1008.geometry}
          material={materials.Palette}
          position={[-1.341, 1.049, 1.888]}
          rotation={[2.022, 0.33, -2.553]}
          scale={0.219}
        />
        <mesh
          name='Plant1009'
          castShadow
          receiveShadow
          geometry={nodes.Plant1009.geometry}
          material={materials.Palette}
          position={[-1.303, 1.058, 2.038]}
          rotation={[1.629, 0.55, -1.682]}
          scale={0.959}
        />
        <mesh
          name='Plant1001'
          castShadow
          receiveShadow
          geometry={nodes.Plant1001.geometry}
          material={materials.Palette}
          position={[4.961, 1.049, 4.851]}
          rotation={[1.391, -0.525, 1.224]}
          scale={0.307}
        />
        <mesh
          name='Plant1002'
          castShadow
          receiveShadow
          geometry={nodes.Plant1002.geometry}
          material={materials.Palette}
          position={[5.238, 1.049, 5.123]}
          rotation={[2.113, -0.112, 2.958]}
          scale={0.388}
        />
        <mesh
          name='Plant1003'
          castShadow
          receiveShadow
          geometry={nodes.Plant1003.geometry}
          material={materials.Palette}
          position={[2.795, 1.049, 5.492]}
          rotation={[1.213, 0.43, -0.839]}
          scale={0.307}
        />
        <mesh
          name='Plant1010'
          castShadow
          receiveShadow
          geometry={nodes.Plant1010.geometry}
          material={materials.Palette}
          position={[2.855, 1.049, 5.109]}
          rotation={[1.142, -0.36, 0.657]}
          scale={0.388}
        />
        <mesh
          name='Plant1011'
          castShadow
          receiveShadow
          geometry={nodes.Plant1011.geometry}
          material={materials.Palette}
          position={[2.606, 1.049, 5.273]}
          rotation={[1.029, 0.114, -0.186]}
          scale={0.225}
        />
        <mesh
          name='Plant1012'
          castShadow
          receiveShadow
          geometry={nodes.Plant1012.geometry}
          material={materials.Palette}
          position={[-4.678, 0.908, 5.555]}
          rotation={[1.813, -0.501, 2.046]}
          scale={0.307}
        />
        <mesh
          name='Plant1013'
          castShadow
          receiveShadow
          geometry={nodes.Plant1013.geometry}
          material={materials.Palette}
          position={[-4.55, 0.917, 5.468]}
          rotation={[2.08, -0.225, 2.762]}
          scale={0.959}
        />
        <mesh
          name='Plant1014'
          castShadow
          receiveShadow
          geometry={nodes.Plant1014.geometry}
          material={materials.Palette}
          position={[-3.904, 0.861, 5.827]}
          rotation={[1.915, 0.441, -2.269]}
          scale={0.307}
        />
        <mesh
          name='Plant1015'
          castShadow
          receiveShadow
          geometry={nodes.Plant1015.geometry}
          material={materials.Palette}
          position={[-3.895, 0.871, 5.982]}
          rotation={[1.51, 0.549, -1.455]}
          scale={0.959}
        />
        <group
          name='Arbre_1002'
          position={[7.021, 1.928, 3.009]}
          rotation={[-2.94, 0.522, 3.09]}
          scale={[0.748, 0.838, 0.748]}
        >
          <mesh
            name='Icosphere044'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere044.geometry}
            material={materials.Arbre10}
          />
          <mesh
            name='Icosphere044_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere044_1.geometry}
            material={materials.Arbre11}
          />
          <mesh
            name='Icosphere044_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere044_2.geometry}
            material={materials.Planches}
          />
        </group>
        <mesh
          name='Arbre_1019'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1019.geometry}
          material={materials.Chene_128}
          position={[7.006, 0.934, 6.757]}
          rotation={[-1.955, -1.534, -1.811]}
          scale={[1.621, 1.815, 1.621]}
        />
        <group
          name='Icosphere'
          position={[-1.075, 1.035, -3.094]}
          scale={0.167}
        >
          <mesh
            name='Icosphere009_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_1.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere009_2'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere009_2.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere001'
          position={[-0.909, 1.035, -2.686]}
          rotation={[Math.PI, -1.412, Math.PI]}
          scale={0.193}
        >
          <mesh
            name='Icosphere010'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere010.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere010_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere010_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere002'
          position={[-0.692, 1.035, -2.227]}
          rotation={[0, -0.673, 0]}
          scale={0.167}
        >
          <mesh
            name='Icosphere011'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere011.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere011_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere011_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere003'
          position={[-4.232, 0.942, -1.341]}
          rotation={[-Math.PI, 0.514, -Math.PI]}
          scale={0.177}
        >
          <mesh
            name='Icosphere012'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere012.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere012_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere012_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere004'
          position={[-4.176, 0.942, -1.778]}
          rotation={[0, 0.897, 0]}
          scale={0.152}
        >
          <mesh
            name='Icosphere013'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere013.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere013_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere013_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere005'
          position={[-4.138, 0.942, -2.285]}
          rotation={[-Math.PI, 1.187, -Math.PI]}
          scale={0.167}
        >
          <mesh
            name='Icosphere014'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere014.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere014_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere014_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere006'
          position={[0.323, 1.361, -6.038]}
          rotation={[0, 0.897, 0]}
          scale={0.201}
        >
          <mesh
            name='Icosphere015'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere015.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere015_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere015_1.geometry}
            material={materials.Planches}
          />
        </group>
        <mesh
          name='Icosphere007'
          castShadow
          receiveShadow
          geometry={nodes.Icosphere007.geometry}
          material={materials.Pin512}
          position={[2.032, 1.071, 0.426]}
          rotation={[-Math.PI, 1.187, -Math.PI]}
          scale={0.268}
        />
        <group
          name='Icosphere008'
          position={[1.45, 1.071, 0.303]}
          rotation={[-Math.PI, 0.227, -Math.PI]}
          scale={0.196}
        >
          <mesh
            name='Icosphere061'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere061.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere061_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere061_1.geometry}
            material={materials.Planches}
          />
        </group>
        <group
          name='Icosphere009'
          position={[2.414, 1.071, -0.217]}
          rotation={[-Math.PI, 1.007, -Math.PI]}
          scale={0.217}
        >
          <mesh
            name='Icosphere062'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere062.geometry}
            material={materials.Pin512}
          />
          <mesh
            name='Icosphere062_1'
            castShadow
            receiveShadow
            geometry={nodes.Icosphere062_1.geometry}
            material={materials.Planches}
          />
        </group>
        <mesh
          name='Arbre_1033'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1033.geometry}
          material={materials.Chene_128}
          position={[-4.768, 1.381, 9.362]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1011'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1011.geometry}
          material={materials.Chene_128}
          position={[6.546, 1.975, 2.902]}
          rotation={[-0.049, 0.797, 0.179]}
          scale={[1.612, 1.804, 1.612]}
        />
        <mesh
          name='Arbre_1012'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1012.geometry}
          material={materials.Chene_128}
          position={[6.952, 1.903, 3.649]}
          rotation={[0.063, -0.121, 0.11]}
          scale={[1.246, 1.395, 1.246]}
        />
        <mesh
          name='Arbre_1025'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1025.geometry}
          material={materials.Chene_128}
          position={[7.253, 2.038, 3.009]}
          rotation={[-2.879, 1.437, 3.025]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1004'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1004.geometry}
          material={materials.Chene_128}
          position={[8.033, 1.567, -0.51]}
          rotation={[-3.103, -0.438, -2.981]}
          scale={[1.291, 1.446, 1.291]}
        />
        <mesh
          name='Arbre_1006'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1006.geometry}
          material={materials.Chene_128}
          position={[8.509, 1.273, 0.365]}
          rotation={[3.071, 0.479, -3.007]}
          scale={[0.998, 1.118, 0.998]}
        />
        <mesh
          name='Arbre_1007'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1007.geometry}
          material={materials.Chene_128}
          position={[8.775, 1.178, -0.339]}
          rotation={[-2.991, -1.338, -2.851]}
          scale={[0.585, 0.655, 0.585]}
        />
        <mesh
          name='Arbre_1013'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1013.geometry}
          material={materials.Chene_128}
          position={[3.505, 1.403, -6.966]}
          rotation={[-0.046, -0.712, 0.114]}
          scale={[1.239, 1.388, 1.239]}
        />
        <mesh
          name='Arbre_1014'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1014.geometry}
          material={materials.Chene_128}
          position={[2.108, 1.34, -6.907]}
          rotation={[-0.006, 0.382, -0.027]}
          scale={[1.055, 1.181, 1.055]}
        />
        <mesh
          name='Arbre_1015'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1015.geometry}
          material={materials.Chene_128}
          position={[3.379, 1.46, -6.215]}
          rotation={[-0.035, 0.189, 0.151]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1016'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1016.geometry}
          material={materials.Chene_128}
          position={[-5.617, 1.082, 2.617]}
          rotation={[-0.036, 0.302, 0.155]}
          scale={[1.648, 1.845, 1.648]}
        />
        <mesh
          name='Arbre_1017'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1017.geometry}
          material={materials.Chene_128}
          position={[-5.614, 1.077, 3.613]}
          rotation={[0.076, -0.615, 0.146]}
          scale={[1.46, 1.635, 1.46]}
        />
        <mesh
          name='Arbre_1018'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1018.geometry}
          material={materials.Chene_128}
          position={[-5.045, 1.041, 3.121]}
          rotation={[-0.096, 1.202, 0.234]}
          scale={[0.856, 0.958, 0.856]}
        />
        <mesh
          name='Arbre_1009'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1009.geometry}
          material={materials.Chene_128}
          position={[-4.312, 1.466, 8.055]}
          rotation={[-1.741, -1.525, -1.678]}
          scale={[1.46, 1.635, 1.46]}
        />
        <mesh
          name='Arbre_1010'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1010.geometry}
          material={materials.Chene_128}
          position={[-3.578, 1.252, 8.223]}
          rotation={[-0.025, 0.258, 0.079]}
          scale={[0.966, 1.082, 0.966]}
        />
        <mesh
          name='Arbre_1008'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1008.geometry}
          material={materials.Chene_128}
          position={[1.191, 1.381, 7.856]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1020'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1020.geometry}
          material={materials.Chene_128}
          position={[-3.886, 1.087, 2.585]}
          rotation={[-0.097, 0.34, 0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1026'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1026.geometry}
          material={materials.Chene_128}
          position={[-5.04, 0.905, -3.386]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1030'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1030.geometry}
          material={materials.Chene_128}
          position={[3.763, 1.212, 3.526]}
          rotation={[-0.097, 0.34, 0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1031'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1031.geometry}
          material={materials.Chene_128}
          position={[4.167, 1.319, 3.228]}
          rotation={[-0.098, -0.36, -0.029]}
          scale={0.508}
        />
        <mesh
          name='Arbre_1032'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1032.geometry}
          material={materials.Chene_128}
          position={[6.647, 0.908, 6.679]}
          rotation={[-0.32, -1.275, -0.301]}
          scale={0.41}
        />
        <mesh
          name='Arbre_1034'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1034.geometry}
          material={materials.Chene_128}
          position={[6.647, 0.908, 6.253]}
          rotation={[-0.105, -0.512, -0.046]}
          scale={0.61}
        />
        <mesh
          name='Arbre_1035'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1035.geometry}
          material={materials.Chene_128}
          position={[3.788, 1.212, 3.165]}
          rotation={[-3.041, -0.418, -3.095]}
          scale={0.372}
        />
        <mesh
          name='Arbre_1027'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1027.geometry}
          material={materials.Chene_128}
          position={[1.98, 1.142, -0.212]}
          rotation={[-3.048, -0.185, -3.118]}
          scale={0.492}
        />
        <mesh
          name='Arbre_1028'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1028.geometry}
          material={materials.Chene_128}
          position={[1.622, 1.166, -0.025]}
          rotation={[-3.036, 0.514, 3.096]}
          scale={0.409}
        />
        <mesh
          name='Arbre_1029'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1029.geometry}
          material={materials.Chene_128}
          position={[1.915, 1.142, 0.072]}
          rotation={[-0.095, 0.264, 0.031]}
          scale={0.3}
        />
        <mesh
          name='Arbre_1021'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1021.geometry}
          material={materials.Chene_128}
          position={[2.701, 0.992, -3.937]}
          rotation={[-3.032, 0.571, 3.088]}
          scale={0.671}
        />
        <mesh
          name='Arbre_1003'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1003.geometry}
          material={materials.Chene_128}
          position={[3.606, 1.085, -3.178]}
          rotation={[3.126, 0.138, -3.102]}
          scale={[1.148, 1.285, 1.148]}
        />
        <mesh
          name='Arbre_1001'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1001.geometry}
          material={materials.Chene_128}
          position={[-0.048, 1.153, -5.599]}
          rotation={[-0.102, -0.452, -0.039]}
          scale={0.611}
        />
        <mesh
          name='Arbre_1005'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1005.geometry}
          material={materials.Chene_128}
          position={[0.022, 1.153, -5.165]}
          rotation={[-0.149, 0.904, 0.123]}
          scale={0.396}
        />
        <mesh
          name='Arbre_1022'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1022.geometry}
          material={materials.Chene_128}
          position={[4.753, 1.44, 3.341]}
          rotation={[-2.918, -0.944, -2.944]}
          scale={0.533}
        />
        <mesh
          name='Arbre_1023'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1023.geometry}
          material={materials.Chene_128}
          position={[4.62, 1.323, 3.759]}
          rotation={[-3.022, -0.25, -3.074]}
          scale={0.444}
        />
        <mesh
          name='Arbre_1024'
          castShadow
          receiveShadow
          geometry={nodes.Arbre_1024.geometry}
          material={materials.Chene_128}
          position={[4.917, 1.43, 3.611]}
          rotation={[-0.103, 1.034, 0.088]}
          scale={0.325}
        />
        <mesh
          name='ArbreMort_2'
          castShadow
          receiveShadow
          geometry={nodes.ArbreMort_2.geometry}
          material={materials.Palette}
          position={[6.535, 2.632, -2.662]}
          rotation={[-2.952, -0.205, -3.09]}
          scale={0.65}
        />
        <mesh
          name='ArbreMort_1'
          castShadow
          receiveShadow
          geometry={nodes.ArbreMort_1.geometry}
          material={materials.Palette}
          position={[6.335, 3.046, 0.546]}
          rotation={[-Math.PI, 0.886, -Math.PI]}
        />
        <mesh
          name='Cube'
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials.Palette}
          position={[2.4, 1.009, 5.333]}
          rotation={[0, -0.772, 0]}
        />
        <mesh
          name='Cube001'
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Palette}
          position={[3.618, 1.009, 6.518]}
          rotation={[0.096, -0.842, 0.211]}
          scale={0.801}
        />
        <mesh
          name='Cube002'
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials.Palette}
          position={[4.787, 1.556, 2.987]}
          rotation={[2.975, -0.75, 2.652]}
          scale={0.801}
        />
        <mesh
          name='Cube003'
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials.Palette}
          position={[3.428, 1.009, 4.156]}
          rotation={[Math.PI, -0.809, Math.PI]}
        />
        <mesh
          name='Cube004'
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials.Palette}
          position={[5.632, 1.032, 8.763]}
          rotation={[0.138, 0.736, -0.122]}
          scale={0.801}
        />
        <mesh
          name='Cube005'
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials.Palette}
          position={[4.628, 1.237, 7.665]}
          rotation={[-0.181, -0.825, -0.246]}
          scale={0.801}
        />
        <mesh
          name='Cube006'
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={materials.Palette}
          position={[6.787, 0.99, 7.678]}
          rotation={[0.089, 0.748, -0.074]}
          scale={0.801}
        />
        <mesh
          name='Cube007'
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={materials.Palette}
          position={[7.962, 1.009, 6.581]}
          rotation={[-Math.PI, 0.804, -Math.PI]}
          scale={0.801}
        />
        <mesh
          name='Cube008'
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={materials.Palette}
          position={[6.783, 1.093, 5.357]}
          rotation={[-3.026, 0.917, -2.969]}
          scale={0.801}
        />
        <mesh
          name='Cube009'
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Palette}
          position={[5.815, 1.414, 4.07]}
          rotation={[-2.982, 0.816, 3.05]}
          scale={0.801}
        />
        <mesh
          name='HP_Clôture002'
          castShadow
          receiveShadow
          geometry={nodes.HP_Clôture002.geometry}
          material={materials.Palette}
          position={[1.426, 1.77, -4.619]}
          rotation={[0, 1.09, 0]}
          scale={[1, 1.743, 1]}
        />
        <mesh
          name='Land'
          castShadow
          receiveShadow
          geometry={nodes.Land.geometry}
          material={materials.Ground}
        />
        <mesh
          name='SousSol'
          castShadow
          receiveShadow
          geometry={nodes.SousSol.geometry}
          material={materials.Palette}
        />
        <group name='Lampadaire_2001' position={[3.458, 1.108, 4.046]}>
          <mesh
            name='Cylinder002'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder002_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2002' position={[-0.178, 1.122, -3.173]}>
          <mesh
            name='Cylinder003'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder003_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2003' position={[1.018, 1.199, -2.521]}>
          <mesh
            name='Cylinder004'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2004' position={[4.572, 1.516, -0.864]}>
          <mesh
            name='Cylinder005'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder005_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaire_2005' position={[4.558, 1.467, -1.374]}>
          <mesh
            name='Cylinder006'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder006_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='Lampadaires_1' position={[-2.358, 1.346, -0.099]}>
          <mesh
            name='Cylinder026'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026.geometry}
            material={materials.Palette}
          />
          <mesh
            name='Cylinder026_1'
            castShadow
            receiveShadow
            geometry={nodes.Cylinder026_1.geometry}
            material={materials.PaletteLumiere}
          />
        </group>
        <group name='ArmatureDusty' position={[0, 1.914, 0]}>
          <skinnedMesh
            name='Dusty'
            geometry={nodes.Dusty.geometry}
            material={materials.DustySkin}
            skeleton={nodes.Dusty.skeleton}
            morphTargetDictionary={nodes.Dusty.morphTargetDictionary}
            morphTargetInfluences={nodes.Dusty.morphTargetInfluences}
          />
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
        <mesh
          name='Socle'
          castShadow
          receiveShadow
          geometry={nodes.Socle.geometry}
          material={materials.Palette}
          position={[0, 1.07, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('/game/Land.glb');
