/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function StatuePingu({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/StatuePingu.glb');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  const initialMaterial1 = materials.PinguEyesBlack.clone();
  const highlightMaterial1 = initialMaterial1.clone();
  highlightMaterial1.color.set(color);

  const initialMaterial2 = materials.Couronne_Or.clone();
  const highlightMaterial2 = initialMaterial2.clone();
  highlightMaterial2.color.set(color);

  const initialMaterial3 = materials.Couronne_Saphir.clone();
  const highlightMaterial3 = initialMaterial3.clone();
  highlightMaterial3.color.set(color);

  const initialMaterial4 = materials.Couronne_Tour.clone();
  const highlightMaterial4 = initialMaterial4.clone();
  highlightMaterial4.color.set(color);

  const initialMaterial5 = materials.Bijou_Or.clone();
  const highlightMaterial5 = initialMaterial5.clone();
  highlightMaterial5.color.set(color);

  const initialMaterial6 = materials.PinguEyesBlue.clone();
  const highlightMaterial6 = initialMaterial6.clone();
  highlightMaterial6.color.set(color);

  const initialMaterial7 = materials.PinguEyesWhite.clone();
  const highlightMaterial7 = initialMaterial7.clone();
  highlightMaterial7.color.set(color);

  const initialMaterial8 = materials.PinguSkinBlack.clone();
  const highlightMaterial8 = initialMaterial8.clone();
  highlightMaterial8.color.set(color);

  const initialMaterial9 = materials.PinguSkinPink.clone();
  const highlightMaterial9 = initialMaterial9.clone();
  highlightMaterial9.color.set(color);

  const initialMaterial10 = materials.PinguSkinWhite.clone();
  const highlightMaterial10 = initialMaterial10.clone();
  highlightMaterial10.color.set(color);

  const initialMaterial11 = materials.PinguBeak.clone();
  const highlightMaterial11 = initialMaterial11.clone();
  highlightMaterial11.color.set(color);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='PinguFrenStatue' position={[0, 1.93, 0]}>
          <mesh
            name='Cube004'
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={color ? highlightMaterial1 : initialMaterial1}
          />
          <mesh
            name='Cube004_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={color ? highlightMaterial2 : initialMaterial2}
          />
          <mesh
            name='Cube004_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_2.geometry}
            material={color ? highlightMaterial3 : initialMaterial3}
          />
          <mesh
            name='Cube004_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_3.geometry}
            material={color ? highlightMaterial4 : initialMaterial4}
          />
          <mesh
            name='Cube004_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_4.geometry}
            material={color ? highlightMaterial5 : initialMaterial5}
          />
          <mesh
            name='Cube004_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_5.geometry}
            material={color ? highlightMaterial6 : initialMaterial6}
          />
          <mesh
            name='Cube004_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_6.geometry}
            material={color ? highlightMaterial7 : initialMaterial7}
          />
          <mesh
            name='Cube004_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_7.geometry}
            material={color ? highlightMaterial8 : initialMaterial8}
          />
          <mesh
            name='Cube004_8'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_8.geometry}
            material={color ? highlightMaterial9 : initialMaterial9}
          />
          <mesh
            name='Cube004_9'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_9.geometry}
            material={color ? highlightMaterial10 : initialMaterial10}
          />
          <mesh
            name='Cube004_10'
            castShadow
            receiveShadow
            geometry={nodes.Cube004_10.geometry}
            material={color ? highlightMaterial11 : initialMaterial11}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/StatuePingu.glb');
