/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function TavernEmpty({ position, color, rotation, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/TavernEmpty.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name='CrypteBlanche'
        castShadow
        receiveShadow
        geometry={nodes.CrypteBlanche.geometry}
        material={materials.CrypteBlanche}
        position={position}
        scale={[0.25, 0.25, 0.25]}
        rotation={rotation}
      >
        <meshStandardMaterial color={color} transparent />
      </mesh>
    </group>
  );
}

useGLTF.preload('/game/TavernEmpty.glb');
