/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function TavernR2({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Tavern+2.glb');
  const { actions } = useAnimations(animations, group);

  const position = [4.435, 1.067, 5.3641];
  const rotation = [0, -2.2521728667735, 0];

  useEffect(() => {
    actions['ArmatureAction.001'].play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <>
          <spotLight
            position={[4.3041, 1.9694, 5.1689]}
            color={'yellow'}
            power={10}
            angle={0.85}
          />

          <spotLight
            position={[5.5716, 1.9694, 5.4831]}
            color={'yellow'}
            power={10}
            angle={0.85}
          />

          <spotLight
            position={[5.5124, 1.9694, 6.564]}
            color={'yellow'}
            power={10}
            angle={0.85}
          />

          <spotLight
            position={[4.9129, 1.5467, 6.6745]}
            color={'yellow'}
            power={10}
            angle={0.85}
          />

          <spotLight
            position={[4.1262, 1.5467, 6.072]}
            color={'yellow'}
            power={10}
            angle={0.85}
          />

          <pointLight
            position={[4.9558, 1.8621, 5.7825]}
            power={10}
            color={'yellow'}
          />
        </>
      )}
      <group name='Scene'>
        <mesh
          name='Tonneaux'
          castShadow
          receiveShadow
          geometry={nodes.Tonneaux.geometry}
          material={materials.Tonneau}
        >
          {color !== undefined && (
            <meshStandardMaterial color={color} transparent opacity={0.2} />
          )}
        </mesh>
        <group name='Interieur'>
          <mesh
            name='Cube036'
            castShadow
            receiveShadow
            geometry={nodes.Cube036.geometry}
            material={materials.Palette}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_1.geometry}
            material={materials.SkBase}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_2.geometry}
            material={materials.SkShadow}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_3.geometry}
            material={materials.SkTeeth}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_4.geometry}
            material={materials.LanterneVerreLumière}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_5.geometry}
            material={materials.Tabouret}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_6.geometry}
            material={materials['Planches.001']}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube036_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_7.geometry}
            material={materials.Portrait}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
        </group>
        <group name='Taverne+2'>
          <mesh
            name='Cube002'
            castShadow
            receiveShadow
            geometry={nodes.Cube002.geometry}
            material={materials.MursBardageBleu}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_1.geometry}
            material={materials['Planches.001']}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_2.geometry}
            material={materials.Vitraux}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_3.geometry}
            material={materials.VitresLumière}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_4.geometry}
            material={materials.Palette}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_5.geometry}
            material={materials.LanterneVerreLumière}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_6.geometry}
            material={materials['Cheminée.001']}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_7.geometry}
            material={materials.Porte_1}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_8'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_8.geometry}
            material={materials.Floor}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_9'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_9.geometry}
            material={materials.Poutre_Inst}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
          <mesh
            name='Cube002_10'
            castShadow
            receiveShadow
            geometry={nodes.Cube002_10.geometry}
            material={materials.ArdoisesVertes}
          >
            {color !== undefined && (
              <meshStandardMaterial color={color} transparent opacity={0.2} />
            )}
          </mesh>
        </group>
        <group
          name='Armature'
          position={[3.838, 1.035, 5.343]}
          rotation={[Math.PI, -0.875, Math.PI]}
          scale={0.4}
        >
          <group name='Crâne001'>
            <skinnedMesh
              name='Sphere016'
              geometry={nodes.Sphere016.geometry}
              material={materials['Skeleton.001']}
              skeleton={nodes.Sphere016.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere016_1'
              geometry={nodes.Sphere016_1.geometry}
              material={materials.Material}
              skeleton={nodes.Sphere016_1.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere016_2'
              geometry={nodes.Sphere016_2.geometry}
              material={materials['Material.002']}
              skeleton={nodes.Sphere016_2.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere016_3'
              geometry={nodes.Sphere016_3.geometry}
              material={materials['Material.001']}
              skeleton={nodes.Sphere016_3.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
            <skinnedMesh
              name='Sphere016_4'
              geometry={nodes.Sphere016_4.geometry}
              material={materials.BouteilleEtiquette}
              skeleton={nodes.Sphere016_4.skeleton}
            >
              {color !== undefined && (
                <meshStandardMaterial color={color} transparent opacity={0.2} />
              )}
            </skinnedMesh>
          </group>
          <primitive object={nodes.mixamorigHips} />
          <primitive object={nodes.Ctrl_Master} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Left} />
          <primitive object={nodes.Ctrl_Hand_IK_Left} />
          <primitive object={nodes.Ctrl_ArmPole_IK_Right} />
          <primitive object={nodes.Ctrl_Hand_IK_Right} />
          <primitive object={nodes.Ctrl_Foot_IK_Left} />
          <primitive object={nodes.Ctrl_LegPole_IK_Left} />
          <primitive object={nodes.Ctrl_Foot_IK_Right} />
          <primitive object={nodes.Ctrl_LegPole_IK_Right} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/Tavern+2.glb');
