/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { Color, MeshStandardMaterial } from 'three';

export function TavernR1({ color, ...props }: any) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/game/Tavern+1.glb');
  const { actions } = useAnimations(animations, group);

  const emptyMaterial = new MeshStandardMaterial();
  emptyMaterial.color = new Color(color);
  emptyMaterial.transparent = true;
  emptyMaterial.opacity = 0.2;

  useEffect(() => {
    actions.Action.play();
  }, [group]);

  return (
    <group ref={group} {...props} dispose={null}>
      {color === undefined && (
        <>
          <pointLight
            position={[4.3041, 1.9694, 5.1689]}
            color={'yellow'}
            power={10}
          />

          <pointLight
            position={[5.5716, 1.9694, 5.4831]}
            color={'yellow'}
            power={10}
          />

          <pointLight
            position={[5.5124, 1.9694, 6.564]}
            color={'yellow'}
            power={10}
          />

          <pointLight
            position={[4.9129, 1.5467, 6.6745]}
            color={'yellow'}
            power={10}
          />

          <pointLight
            position={[4.1262, 1.5467, 6.072]}
            color={'yellow'}
            power={10}
          />

          <pointLight
            position={[4.9558, 1.8621, 5.7825]}
            power={10}
            color={'yellow'}
          />
        </>
      )}
      <group name='Scene'>
        <mesh
          name='Tonneaux'
          castShadow
          receiveShadow
          geometry={nodes.Tonneaux.geometry}
          material={color ? emptyMaterial : materials.Tonneau}
        />
        <mesh
          name='Fantom'
          castShadow
          receiveShadow
          geometry={nodes.Fantom.geometry}
          material={color ? emptyMaterial : materials.Fantom1}
          morphTargetDictionary={nodes.Fantom.morphTargetDictionary}
          morphTargetInfluences={nodes.Fantom.morphTargetInfluences}
          position={[3.761, 1.489, 4.818]}
          rotation={[-3.063, -1.519, -3.124]}
        />
        <group name='Taverne+1'>
          <mesh
            name='Cube007'
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={color ? emptyMaterial : materials.MursPierresOcre}
          />
          <mesh
            name='Cube007_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={color ? emptyMaterial : materials['Planches.001']}
          />
          <mesh
            name='Cube007_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_2.geometry}
            material={color ? emptyMaterial : materials.Vitraux}
          />
          <mesh
            name='Cube007_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_3.geometry}
            material={color ? emptyMaterial : materials.VitresLumière}
          />
          <mesh
            name='Cube007_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_4.geometry}
            material={color ? emptyMaterial : materials.Palette}
          />
          <mesh
            name='Cube007_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_5.geometry}
            material={color ? emptyMaterial : materials.LanterneVerreLumière}
          />
          <mesh
            name='Cube007_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_6.geometry}
            material={color ? emptyMaterial : materials['Cheminée.001']}
          />
          <mesh
            name='Cube007_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_7.geometry}
            material={color ? emptyMaterial : materials.Porte_1}
          />
          <mesh
            name='Cube007_8'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_8.geometry}
            material={color ? emptyMaterial : materials.Floor}
          />
          <mesh
            name='Cube007_9'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_9.geometry}
            material={color ? emptyMaterial : materials.Poutre_Inst}
          />
          <mesh
            name='Cube007_10'
            castShadow
            receiveShadow
            geometry={nodes.Cube007_10.geometry}
            material={color ? emptyMaterial : materials.ArdoisesRouges}
          />
        </group>
        <group name='Interieur'>
          <mesh
            name='Cube036'
            castShadow
            receiveShadow
            geometry={nodes.Cube036.geometry}
            material={color ? emptyMaterial : materials.Palette}
          />
          <mesh
            name='Cube036_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_1.geometry}
            material={color ? emptyMaterial : materials.SkBase}
          />
          <mesh
            name='Cube036_2'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_2.geometry}
            material={color ? emptyMaterial : materials.SkShadow}
          />
          <mesh
            name='Cube036_3'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_3.geometry}
            material={color ? emptyMaterial : materials.SkTeeth}
          />
          <mesh
            name='Cube036_4'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_4.geometry}
            material={color ? emptyMaterial : materials.LanterneVerreLumière}
          />
          <mesh
            name='Cube036_5'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_5.geometry}
            material={color ? emptyMaterial : materials.Tabouret}
          />
          <mesh
            name='Cube036_6'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_6.geometry}
            material={color ? emptyMaterial : materials['Planches.001']}
          />
          <mesh
            name='Cube036_7'
            castShadow
            receiveShadow
            geometry={nodes.Cube036_7.geometry}
            material={color ? emptyMaterial : materials.Portrait}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/game/Tavern+1.glb');
