/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Tavern({ position, color, rotation, ...props }: any) {
  const { nodes, materials } = useGLTF('/game/Tavern.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        name='Crypte'
        castShadow
        receiveShadow
        geometry={nodes.Crypte.geometry}
        material={materials.Crypte}
        position={position}
        scale={[0.25, 0.25, 0.25]}
        rotation={rotation}
      >
        {color !== undefined && (
          <meshStandardMaterial color={color} transparent />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload('/game/Tavern.glb');
